### ISSUE TITLE
Wat and wasm compilation

### ISSUE THREAD

**Issue by adam314315** [notgiven688/webminerpool#10]
Hello,

I am really interested by the asm and wasm technology and would like to better understand the process to generate it from the C / C++ libraries. I understand wat was the wasm source code but not fully the overall process. Could you please describe a little bit the different steps to generate them for the cyrptonight C libraries provided in the webassembly > xmr folder for instance ?

Thanks Adam.

**Comment by gitmanfa** [comment]
Yes please tell the steps to compile Thanks

**Comment by notgiven688** [comment]
@gitmanfa install emscripten. Make sure "emcc" is available. Then try
"make clean" and "make".

**Comment by BackToPyramidOne** [comment]
@notgiven688 The file cryptonight.o is not present. touch cryptonight.o ?
