### ISSUE TITLE
fatal error 'variant4_random_math.h' file not found 

### ISSUE THREAD

**Issue by ChristianGrieger** [notgiven688/webminerpool#103]
When I try to make the libhash.io file i get this error:

`$ make -f Makefile
gcc -O3 -shared -pthread -fPIC -g -Wall -std=gnu99 -maes   -c -o cryptonight.o cryptonight.c
clang: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
cryptonight.c:11:10: fatal error: 'variant4_random_math.h' file not found
#include "variant4_random_math.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [cryptonight.o] Error 1`

Is there anything I'am doing wrong?

**Comment by VidYen** [comment]
I am getting a similar error by running `make` in both either the `libhash` or `webassembly` directories:

In libhash directory:
```
webminerpool/hash_cn/libhash$ make
gcc -O3 -shared -pthread -fPIC -g -Wall -std=gnu99 -maes   -c -o cryptonight.o cryptonight.c
cryptonight.c:11:34: fatal error: variant4_random_math.h: No such file or directory
 #include "variant4_random_math.h"
                                  ^
compilation terminated.
<builtin>: recipe for target 'cryptonight.o' failed
make: *** [cryptonight.o] Error 1
```

And and webassembly:

```
webminerpool/hash_cn/webassembly$ make
emcc -O3 -s NO_FILESYSTEM=1 -s 'EXTRA_EXPORTED_RUNTIME_METHODS=["ccall", "cwrap"]'  --llvm-lto 1 -s TOTAL_MEMORY=67108864  -s WASM=1 -s "BINARYEN_TRAP_MODE='allow'" -s EXPORTED_FUNCTIONS="['_hash_cn']"  --shell-file html_template/shell_minimal.html -Wall    -c -o cryptonight.o cryptonight.c
/bin/sh: 1: emcc: not found
<builtin>: recipe for target 'cryptonight.o' failed
make: *** [cryptonight.o] Error 127
```

Just pulled from the repo about 15 minutes ago. The server.exe seems to be able to run it seems though.

**Comment by notgiven688** [comment]
@ChristianGrieger @VidYen Fixed in https://github.com/notgiven688/webminerpool/commit/25198f73e1e5f39719dbb82e7c763ed295fa6695 Basically you can use the file from the webassembly folder.

**Comment by ChristianGrieger** [comment]
thanks!
