### ISSUE TITLE
libhash.so not detected but in folder

### ISSUE THREAD

**Issue by ChristianGrieger** [notgiven688/webminerpool#104]
I compiled it but it does not get detected. Its in the folder. Anything i am doing wrong?

**Comment by notgiven688** [comment]
Probably ;) What does the console say?

**Comment by ChristianGrieger** [comment]
that the file cant be found like if its not in

**Comment by ChristianGrieger** [comment]
<img width="481" alt="bildschirmfoto 2019-03-01 um 20 47 08" src="https://user-images.githubusercontent.com/8712219/53662464-3d563700-3c63-11e9-90aa-4b5dbfb3a69d.png">

**Comment by ChristianGrieger** [comment]
Compiled it again on server and problem seems to be gone.

**Comment by daniel-lucio** [comment]
Yes, seems that it has to be compiled twice.

**Comment by daniel-lucio** [comment]
Mono: DllImport attempting to load: 'libhash.so'.
Mono: DllImport loaded library '/usr/local/bin/libhash.so'.
Mono: DllImport searching in: 'libhash.so' ('/usr/local/bin/libhash.so').
Mono: Searching for 'hash_cn'.
Mono: Probing 'hash_cn'.
Mono: Found as 'hash_cn'.
Mono: DllImport searching in: 'libhash.so' ('/usr/local/bin/libhash.so').
**Mono: Searching for 'hash_free'.
Mono: Probing 'hash_free'.
Mono: Found as 'hash_free'.
libhash.so is not available. Checking user submitted hashes disabled:**
 -> System.Exception: Hash function returned wrong hash

I think it has something to do with the way the .so is linked
