### ISSUE TITLE
How to Embed a Wallet Address in Pools JSON

### ISSUE THREAD

**Issue by dx908** [notgiven688/webminerpool#105]
Thank you so much for creating this. Works perfectly.

I was just wondering how can I embed a wallet address inside Pools.json?

I know currently the wallet needs to be passed to StartMining function. But this makes the wallet address public and someone can copy and paste on some popular pools to check Hashrate of my miners.

My goal is to make my wallet address private. If I embed that in webmr.js, that still makes it public because someone can go through it's source to see it.

As this project works as a full proxy node to pool and aggregates all hashes then there should be a way to embed that wallet inside Pools.JSON?

Because only that will make it private and untraceable.

For example something like this in `/root/webminerpool/server/pools.json`

` "moneroocean.stream" : { "url" : "gulf.moneroocean.stream", "port" : 10001, "login": "walletaddress", "emptypassword" : "x", "algorithm" : "cn" },`

and then in StartMining Function I only Pass the Pool name e.g.

`startMining("moneroocean.stream","");
`
Let me know if I'm missing something.

Cheers

**Comment by notgiven688** [comment]
Hey.. Check the ReadMe -> StartMiningWithId .. Does this help?

**Comment by dx908** [comment]
Yes you are right. Perfect now.

Sorry my bad, commented in hurry ;)
