### ISSUE TITLE
Antivirus alert

### ISSUE THREAD

**Issue by xmrmining** [notgiven688/webminerpool#107]
hi,
is use compressed version "webmr.js" and eset anti virus blocket it ! but uncompressed ( 3 file) do'nt have any problem whit antivirus,

**Comment by xmrmining** [comment]
also Script don't work :(
in server anythings is Ok but in supportxmr.com my hashrate is 0 !

**Comment by notgiven688** [comment]
Please ask a specific question or try to describe your problem in detail.

**Comment by xmrmining** [comment]
> Please ask a specific question or try to describe your problem in detail.

webmr.js ((compressed version) detected as virus by Eset antivirus. but

**Comment by VidYen** [comment]
@xmrmining This is a known issue with most AV, either rename it or use uncompressed version and rename the miner.js file to something else.
