### ISSUE TITLE
Current algo mining on server 

### ISSUE THREAD

**Issue by patrickbau** [notgiven688/webminerpool#108]
Hello
can you add information on the current algo mined on the server 
![2019-03-11_16-45-01](https://user-images.githubusercontent.com/34626734/54137004-21018980-441d-11e9-832e-fb1ad52bcdd4.png)
like this one
![2019-03-11_16-46-40](https://user-images.githubusercontent.com/34626734/54137131-59a16300-441d-11e9-92dc-29069b9b2ed4.png)

**Comment by notgiven688** [comment]
Yes. Will add it.

**Comment by notgiven688** [comment]
Added with commit 6169301fd86dfb3164323eabd1a613fc77e4bda7

**Comment by patrickbau** [comment]
Thank you it work great
![2019-03-15_10-15-59](https://user-images.githubusercontent.com/34626734/54420855-69fe5a00-470b-11e9-85be-085caf276674.png)
