### ISSUE TITLE
Master branch v8 update issues

### ISSUE THREAD

**Issue by tarikjn** [notgiven688/webminerpool#112]
I pulled updates from the repo to run a quick test and got the following error: 

Client-side:
> {"identifier":"error","param":"lost pool connection."}

Proxy-side:

> Connecting: 172.17.0.1
f7a1fd2d-5c36-490a-9ba4-9c69a5ee4974: connected with ip 172.17.0.1
f7a1fd2d-5c36-490a-9ba4-9c69a5ee4974: handshake - moneroocean.stream, 422QQNhn...
f7a1fd2d-5c36-490a-9ba4-9c69a5ee4974: initiated new pool connection
422QQNhnhX8hmMEkF3TWePWSvKm6DiV7sS3Za2dXrynsJ1w8U6AzwjEdnewdhmP3CDaqvaS6BjEjGMK9mnumtufvLmz5HJi x gulf.moneroocean.stream
f7a1fd2d-5c36-490a-9ba4-9c69a5ee4974: closed
f7a1fd2d-5c36-490a-9ba4-9c69a5ee4974: closed a pool connection.
[03/19/2019 23:50:15] heartbeat; connections client/pool: 0/0; jobqueue: 0.0k; speed: 0.0kH/s

Looks like the default `moneroocean.stream` pool drops the connection, unsure why? I haven't digged deep into yet but figured someone can point in the right direction.

Also, any reason why the git history was rewritten? The last commit before hard fork updates had its commit hash changed, makes it harder to track and inspect changes.

**Comment by VidYen** [comment]
Can you mine with that address on the MO webminer on the dashboard. It’s
rare but same XMR legacy addresses don’t work (I’ve run into this twice
with MoneroOcean)

If it works then try c3pool.com which is a literal copy and paste of the MO
code (with his permission) on a Chinese pool.

**Comment by tarikjn** [comment]
This is the default address in the code. Tried other addresses, and have the same dropped connection after handshake on `moneroocean.stream`.

I tried the `supportxmr.com` pool and got a bit further, connection goes through, until I get disconnected after solving a hash: `got disconnected for WRONG hash`.

Should the version be updated to `8` in the handshake? it's still `7`.

**Comment by VidYen** [comment]
Is this an upgrade by chance? Have you tried a guest profile by chance? It
might be caching the old js files of more than one pool is not working.

**Comment by tarikjn** [comment]
Nope, running tests locally and checked that the build is refreshed.

**Comment by notgiven688** [comment]
@tarikjn  Looks like your client produces wrong hashes. Did you update the server AND the client, i.e. you get the latest Release or master-branch and start the server and the cloent from the SDK ?
