### ISSUE TITLE
Is it compatible with Snipa22/nodejs-pool?

### ISSUE THREAD

**Issue by slayerulan** [notgiven688/webminerpool#113]
Snipa22's proxy ( xmr-node-proxy ) has a special user agent which is xmr-node-proxy.
With that, proxies are handled by nodejs-pool (you can find it on https://github.com/Snipa22/nodejs-pool/blob/76148a0f7da336bdd2f9bd8b1674a15265e5357c/lib/pool.js#L227 ) so that it gives lower difficultly for proxy.

Does webminerpool server support that?

**Comment by notgiven688** [comment]
It should. Why would you like to send lower diff jobs to your clients?
