### ISSUE TITLE
Safari | iOS mobile memory issue

### ISSUE THREAD

**Issue by PiTi2k5** [notgiven688/webminerpool#114]
Hi @notgiven688
following memory issue on safari and iOS mobiles. On MAC OS/iOS
[javascript log](https://www.crypto-webminer.com/Download/1.PNG)

Safari MAC OS --> start mining with 1 or 2 or more threads --> hashes > 8000 h/s --> memory errors
iOS iPhone5s | iPhone7 --> start mining with 1-2 threads --> mininig runs fine, until i increase the threads to 3 or more than same error with 8000+ h/s and memory errors begins
By the way the call navigator.hardwareConcurrency get always the return of 2 on apple devices and not the real threads, there are an extra javascript file for estimate the cpu cores but doesnt help for memory issue.

I tested the miner on Android and it was the same issue on increase the threads (hashing was rising about x1000), 
Samsung S8 --> start mining with 7 threads (navigator.hardwareConcurrency -1 works) --> mining runs fine, until i increase the threads
Now i have an workaround on Android kill all workers with deleteAllWorkers(); and than call addWorkers(threads); with new max threads it runs fine, but workaround doesnt help on apple devices

I have tryed various build parameters with groth memory and so on, but it doesnt fix iOS issue, safari was run with 2 threads but same issue with increase threads

**Comment by PiTi2k5** [comment]
I have tryed some older build https://github.com/notgiven688/webminerpool/commit/aac0cb5399addb618cb97253d9fdcd85c3a77334#diff-d12a9eda097fab130bdf601fe779f4f7

This build is running fine on apple devices and mobiles without workarounds

**Comment by notgiven688** [comment]
I will check this soon.

**Comment by PiTi2k5** [comment]
I have tested all possible algo/variants. All algo with Memory / divider get this issue on apple devices

**Comment by PiTi2k5** [comment]
Workaround for apple safari
Maybe it helps on bug finding.
If i build with -s PRECISE_F32=1 --> MacOS Safari runs fine, i can start mining, adjust the threads on runtime without memory issues
Info for build action: This uses proper 32-bit floating-point values, at the cost of some extra code size overhead.

The last bug is on iphones thread adjustments, mining works only with 1 thread, but if i change the threads after mining start or inital start with more than 1, the issue with memory begins, so i locked the threads to 1 on iphones / ipad for now.

**Comment by notgiven688** [comment]
@PiTi2k5

> I have tryed various build parameters with groth memory and so on
Did you try to increase TOTAL_MEMORY=67108864 ?

**Comment by PiTi2k5** [comment]
Yes, have tryed various optimations without -O3 with -O1/-O2, groth mem, wasm build with wasm file output without inline


TARGET = prog
LIBS = -lm

CC = emcc -O3 -s SINGLE_FILE=1 -s NO_FILESYSTEM=1 -s 'EXTRA_EXPORTED_RUNTIME_METHODS=["ccall", "cwrap"]'  --llvm-lto 1 -s TOTAL_MEMORY=67108864  -s WASM=1 -s "BINARYEN_TRAP_MODE='allow'" -s EXPORTED_FUNCTIONS="['_has']"  --shell-file html_template/shell_minimal.html
CFLAGS =  -Wall 

# -s ASSERTIONS=1
# -s SINGLE_FILE=1
# -s LEGACY_VM_SUPPORT=1
.PHONY: default all clean

default: $(TARGET)
all: default

OBJECTS = $(patsubst %.c, %.o, $(wildcard *.c))
HEADERS = $(wildcard *.h)

%.o: %.c $(HEADERS) $(CC) $(CFLAGS) -c $< -o $@

.PRECIOUS: $(TARGET) $(OBJECTS)

$(TARGET): $(OBJECTS)
	$(CC) $(OBJECTS) -Wall $(LIBS) -o cn.html

clean:
	-rm -f *.o
	-rm -f $(TARGET)

**Comment by PiTi2k5** [comment]
By the way this bug doesnt exist on pure xmr mining or cn-lite on MAC OS Safari, only on some other algo/variants. And on iOS all algos are bugged with high hashrate/mem allocate issue

**Comment by PiTi2k5** [comment]
The only different from old version and new version is the struct constructors. Maybe other mem allocation that can not be handled by apple? It is not the first time that they bugged the webkit :D on iOS 10-10-2 they have bugged the whole wasm 

struct cry_ctx
{
    uint8_t long_state[MEMORY] __attribute((aligned(16)));
    union cn_slow_hash_state state;
    uint8_t text[INIT_SIZE_BYTE] __attribute((aligned(16)));
    uint8_t a[AES_BLOCK_SIZE] __attribute__((aligned(16)));
    uint8_t b[AES_BLOCK_SIZE] __attribute__((aligned(16)));
    uint8_t c[AES_BLOCK_SIZE] __attribute__((aligned(16)));
    uint8_t d[AES_BLOCK_SIZE] __attribute__((aligned(16)));
    uint8_t e[AES_BLOCK_SIZE] __attribute__((aligned(16)));
    uint8_t a1[AES_BLOCK_SIZE] __attribute__((aligned(16)));
    oaes_ctx *aes_ctx;
};

**Comment by PiTi2k5** [comment]
Apple specific issue, can only be fixed with struct ctx and fixed threads on iOS mobiles
