### ISSUE TITLE
visual studio express 2010

### ISSUE THREAD

**Issue by H1-N1** [notgiven688/webminerpool#115]
hi!
what version of visual studio do you use for compiling the source code?
i m using visual studio exepres 2010 but i got alot of error
thanks

**Comment by VidYen** [comment]
I have a link to the version I use in a scrap sheet I made for myself for
Debian installs (click the link for msbuild )

https://github.com/VidYen/webminerpool/blob/master/doc/debian9.md

**Comment by H1-N1** [comment]
thanks for reply
any help for windows?

**Comment by VidYen** [comment]
I thought the newer .NET versions were free?

I mean, the LINUX versions are so I would guess the  Windows would be too...

...unless they don't run on non verified versions of Windows ;)

**Comment by notgiven688** [comment]
@H1-N1 Probably VS2010 does not support the newest .net framework (?). Any reason why you use the 2010 version?
