### ISSUE TITLE
BitTube Beta version mining ready for testing

### ISSUE THREAD

**Issue by PiTi2k5** [notgiven688/webminerpool#120]
If you want try BitTube webmining use this link ;)

https://www.heavy-test.crypto-webminer.com/heavy-test.html

Mining speed is ~ CN/R

**Comment by PiTi2k5** [comment]
Some improvements: BitTube runs now 30-40% faster than CN-R

**Comment by hitmanex** [comment]
why are you posting this on a github with the source code to web mining

**Comment by PiTi2k5** [comment]
Simple answer... After Beta testing, i can create a PR or notgiven can do a merge from my source or his own source for CN-Heavy, CN-Saber (BitTube).

**Comment by hitmanex** [comment]
bitube, more like floptube

**Comment by slayerulan** [comment]
@hitmanex you dont contribute yet sh*tting words, shut up

@PiTi2k5 thanks for your work
