### ISSUE TITLE
trtl hard fork

### ISSUE THREAD

**Issue by focaeppe** [notgiven688/webminerpool#122]
Trtlcoin will fork at 1.8 million blocks, does webminerpool will support new trtl algorithm?

**Comment by PiTi2k5** [comment]
Anyone know an Testnet Turtle pool?

**Comment by PiTi2k5** [comment]
Turtlecoin Fork (Chukwa hashing!?) at Block 1800000 is ready for testing.
Please send me an Testnet pool. :D

**Comment by notgiven688** [comment]
Looks like it is Argon2 hashing. @PiTi1k5 Did you implement this?

**Comment by PiTi2k5** [comment]
Check out https://github.com/PiTi2k5/turtlecoin-crypto/tree/master/src i have added CN/R, CN-Half and +perf 30% on all algos, so hashing speed is the same or little bit faster + it included the Argon2 hashing. Original turtlecoin-crypto lib was terrible slow on webmining, but they offer Node, DLL, SO, JS, WASM in one project :)

**Comment by VidYen** [comment]
Internesting... How does one integrate this into an algo switcher? Or is it ready for that like NotGiven's was?

TBH, for TRTL I made specific servers that only mined it for the games.

**Comment by notgiven688** [comment]
@PiTi2k5 what does +30% perf mean? In comparison to the webminerpool code? Hard to believe that.

**Comment by PiTi2k5** [comment]
Nope, not comparison to the webminerpool. Compared to legacy turtlecoin-crypto lib ;)

**Comment by PiTi2k5** [comment]
> 
> 
> Internesting...
> 
> TBH, for TRTL I made specific servers that only mined it for the games, but a performance would be greatly welcomed regardless.
> 
> Does TRTL performance improve much for mobile devices? That's where I usually target it.

Mobiles runs fine without workaround (iOS fixed threads)

**Comment by PiTi2k5** [comment]
Core i7-8700K @ 4GHz -
--turtle hashing--
turtlecoin-crypto lib = 850 h/s
my turtlecoin-crypto lib fork with new algos and rewrites = ~1280 h/s
webminerpool = ~1280 h/s

--CN/R--
turtlecoin-crypto lib with CN/R impl. = ~28-32 h/s
turtlecoin-crypto lib fork with new algos and rewrites = ~52-55 h/s
webminerpool = ~52-55 h/s

--Interesting stuff-- build without argon2 and only the .c/.h files from src and include folder with -s EXPORTED_FUNCTIONS=.... like webminerpool does
--turtle hashing--
turtlecoin-crypto lib fork with new algos and rewrites = ~1380-1400 h/s
--CN/R--
turtlecoin-crypto lib fork with new algos and rewrites = ~55-60 h/s


Almost the same hashing speed, but it included the Argon2 hashing method. Maybe we can easily integrate agron2 on your webassembly lib. But i like the tidy code on turtlecoin-crypto for example https://github.com/PiTi2k5/turtlecoin-crypto/blob/master/include/hash.h and https://github.com/PiTi2k5/turtlecoin-crypto/blob/master/src/turtlecoin-crypto-js.cpp#L141 ❤️

**Comment by PiTi2k5** [comment]
Core i7-8700K @ 4GHz -
--turtle hashing-- 10min
turtlecoin-crypto lib = 850 h/s
turtlecoin-crypto lib fork with new algos and rewrites = ~1280 h/s
webminerpool = ~1280 h/s

--CN/R-- 10min
turtlecoin-crypto lib with CN/R impl. = ~28-32 h/s
turtlecoin-crypto lib fork with new algos and rewrites = ~53-55 h/s
webminerpool = ~42-44 h/s

--Interesting stuff-- build without argon2 and only the .c/.h files from src and include folder with -s EXPORTED_FUNCTIONS=.... like webminerpool does
--turtle hashing-- 10min
turtlecoin-crypto lib fork with new algos and rewrites = ~1380-1400 h/s
--CN/R--
turtlecoin-crypto lib fork with new algos and rewrites = ~55-60 h/s


Almost the same hashing speed, but it included the Argon2 hashing method. Maybe we can easily integrate agron2 on your webassembly lib. But i like the tidy code on turtlecoin-crypto for example https://github.com/PiTi2k5/turtlecoin-crypto/blob/master/include/hash.h and https://github.com/PiTi2k5/turtlecoin-crypto/blob/master/src/turtlecoin-crypto-js.cpp#L141 ❤️

**Comment by focaeppe** [comment]
Testnet found it in turt discord
publicnode.ydns.eu
![unknown](https://user-images.githubusercontent.com/34982607/60795544-23c28000-a16c-11e9-9694-7f8ae27337b9.png)

**Comment by PiTi2k5** [comment]
Maybe someone can host an testnetpool with this node?

**Comment by PiTi2k5** [comment]
Seems the node/pool is offline. I will check it later. Thanks for information.

**Comment by PiTi2k5** [comment]
<img width="1712" alt="argon2id_chukwa" src="https://user-images.githubusercontent.com/15856741/60928935-7b1d3900-a2af-11e9-9e77-644b3880e77d.png">

Works :)

**Comment by notgiven688** [comment]
@PiTi2k5 Interesting! I might add it. Do you have some numbers how it compares to a native CPU implementation?

**Comment by focaeppe** [comment]
That means turt will be the most profitable for webmining 
![2019-07-10_19-19-56](https://user-images.githubusercontent.com/34982607/60990288-60e36980-a348-11e9-8fc0-8b34f360bd8f.png)

**Comment by PiTi2k5** [comment]
Testing results "single core"
https://github.com/turtlecoin/turtlecoin/issues/716

Argon2 [1 iterations] [8 KB memory]: 43245 H/s
Argon2 [2 iterations] [8 KB memory]: 36203 H/s
Argon2 [3 iterations] [8 KB memory]: 31176 H/s
Argon2 [4 iterations] [8 KB memory]: 27386 H/s
Argon2 [1 iterations] [16 KB memory]: 36395 H/s
Argon2 [2 iterations] [16 KB memory]: 27518 H/s
Argon2 [3 iterations] [16 KB memory]: 22150 H/s
Argon2 [4 iterations] [16 KB memory]: 18511 H/s
Argon2 [1 iterations] [32 KB memory]: 27356 H/s
Argon2 [2 iterations] [32 KB memory]: 18510 H/s
Argon2 [3 iterations] [32 KB memory]: 13983 H/s
Argon2 [4 iterations] [32 KB memory]: 11199 H/s
Argon2 [1 iterations] [64 KB memory]: 18577 H/s
Argon2 [2 iterations] [64 KB memory]: 11211 H/s
Argon2 [3 iterations] [64 KB memory]: 7996 H/s
Argon2 [4 iterations] [64 KB memory]: 6226 H/s
Argon2 [1 iterations] [128 KB memory]: 11268 H/s
Argon2 [2 iterations] [128 KB memory]: 6256 H/s
Argon2 [3 iterations] [128 KB memory]: 4321 H/s
Argon2 [4 iterations] [128 KB memory]: 3318 H/s
Argon2 [1 iterations] [256 KB memory]: 6282 H/s
Argon2 [2 iterations] [256 KB memory]: 3299 H/s
Argon2 [3 iterations] [256 KB memory]: 2251 H/s
Argon2 [4 iterations] [256 KB memory]: 1706 H/s
Argon2 [1 iterations] [512 KB memory]: 3319 H/s
Argon2 [2 iterations] [512 KB memory]: 1696 H/s
Argon2 [3 iterations] [512 KB memory]: 1144 H/s
Argon2 [4 iterations] [512 KB memory]: 860 H/s
Argon2 [1 iterations] [1024 KB memory]: 1141 H/s
Argon2 [2 iterations] [1024 KB memory]: 686 H/s
Argon2 [3 iterations] [1024 KB memory]: 490 H/s
Argon2 [4 iterations] [1024 KB memory]: 381 H/s
Argon2 [1 iterations] [2048 KB memory]: 572 H/s
Argon2 [2 iterations] [2048 KB memory]: 340 H/s
Argon2 [3 iterations] [2048 KB memory]: 244 H/s
Argon2 [4 iterations] [2048 KB memory]: 190 H/s
Argon2 [1 iterations] [4096 KB memory]: 285 H/s
Argon2 [2 iterations] [4096 KB memory]: 170 H/s
Argon2 [3 iterations] [4096 KB memory]: 120 H/s
Argon2 [4 iterations] [4096 KB memory]: 93 H/s

Current planned Turtlecoin fork will use 3 iters / 512 KB mem, maybe they change it before release.

**Comment by notgiven688** [comment]
Okay.. the ratio is interesting, e.g. Argon2[3iterations, native] / Argon2[3iterations, webassembly]. At the moment I do not see why Argon2 with the current parameters can not be implemented more efficiently on the GPU within reasonable time. Why Argon2 is a step in the direction of "making TurtleCoint CPU only coin" (as cited by @focaeppe ) is not clear to me - and I can not make any sense out of that statement. 

In my opinion it is hard to estimate if/how long webmining can be competitive with this algorithm.

**Comment by PiTi2k5** [comment]
<img width="551" alt="Unbenannt" src="https://user-images.githubusercontent.com/15856741/61009183-27275880-a372-11e9-9e1b-e78943a3b01e.PNG">

**Comment by focaeppe** [comment]
@notgiven688 because of the FPGAs

**Comment by PiTi2k5** [comment]
https://github.com/PiTi2k5/webminerpool

Core work is done, hashing works fine. Somethings needs to be added like libhash, CheckHash method... Can you create a branch for argon2 for PRs? Thanks

**Comment by notgiven688** [comment]
@PiTi2k5 https://github.com/notgiven688/webminerpool/tree/argon2

**Comment by notgiven688** [comment]
@PiTi2k5 Works perfectly. Thank You! Going to measure performance. Having a bit of a headache because of file size.

**Comment by notgiven688** [comment]
With a block time of 30s we have 44 days left till the fork. I get ~1/3 of the hashrate of a native implementation - not too bad.

**Comment by focaeppe** [comment]
Is possible to add the miner_compressed for the new algo ?

**Comment by PiTi2k5** [comment]
@focaeppe I think "notgiven" work on this, argon2id - chukwa fork branch needs some additional rewrites on backend server and maybe on hashing lib, it should be ready before fork day :). I have offer the argon2 hashing functions with a PR look at https://github.com/notgiven688/webminerpool/tree/argon2, but i cant work on more rewrites in next days/weeks, because i run my own hashing lib/backend system, it needs some updates and i havnt enough time at the moment.

**Comment by focaeppe** [comment]
@PiTi2k5 Thank you i managed to write it

**Comment by notgiven688** [comment]
It looks like the hashrate of the TRTL fork (argon2/chukwa) is too high to be profitable for web-mining. I will take a closer look at the price/hashrate ratio during the next days to decide if it even makes sense to finalize the TRTL implementation for webminerpool.

**Comment by notgiven688** [comment]
There are first FPGAs you can buy with chukwa (https://bitcointalk.org/index.php?topic=3688965.1080). So probably we are done with TRTL.

**Comment by focaeppe** [comment]
That's really bad the FPGAs was ready before the fork :(
