### ISSUE TITLE
Will Wownero be supported?

### ISSUE THREAD

**Issue by barrettathome** [notgiven688/webminerpool#126]
I see it uses a POW called RandomX.  Just curious if it would be worth it to implement this.

**Comment by focaeppe** [comment]
I think this algo doesn't support auto-algo switching

**Comment by notgiven688** [comment]
@focaeppe I do not understand that answer. RandomX will be the next algorithm for Monero. Sadly enough webassembly does not support the correct rounding modes used in that algorithm, so we would get a very significant performant loss.

**Comment by dx908** [comment]
@notgiven688 I was looking this up and found below link where the a Monero Developer replied in comment that

> To get correct RandomX hashes, you would have to use some soft-fp library (emulated floating point using integer operations).

[https://www.reddit.com/r/MoneroMining/comments/ccwcy4/randomx_in_a_web_browser/](https://www.reddit.com/r/MoneroMining/comments/ccwcy4/randomx_in_a_web_browser/)

So are there any chances you'll work on to integrate next POW in XMR? What are you plans?

**Comment by notgiven688** [comment]
@dx908 Sorry. No plan to have a working version ready for the fork. The outcome of many hours of work would probably be that RandomX does not run fast enough on wasm. We will support the next turtle coin fork. Pools like moneroocean make it possible to still mine and get paid in our favourite crypto - XMR.
