### ISSUE TITLE
[Request] MoneroOcean Pool Auto Algo Switch Option

### ISSUE THREAD

**Issue by dx908** [notgiven688/webminerpool#128]
I was wondering if the option to auto algo switch can be enabled for moneroocean pool. Like I just saw on below link

[https://www.moneroocean.crypto-webminer.com/moneroocean.html](https://www.moneroocean.crypto-webminer.com/moneroocean.html)

Because after the upcoming XMR Hardfork many webmasters will wonder which currency to mine in browsers or which one is most profitable.

I have checked in another thread where user @PiTi2k5 has shared test link for BitTube. From his site I saw this Auto Algo Switching Page. Which seems like awesome replacement.

I think there should be an option in webminerpool config to choose the "MONEROOCEAN POOL AUTO ALGO SWITCH (PAYOUT IN XMR)" which can work in similar fashion. How much feasible is this?

**Comment by VidYen** [comment]
It's actually own by default, but an a simple switch per algo to turn it off would be nice.

I talked to MoneroOcean and currently it will switch to whatever algo the MO pool things is profitable. Usually its CN-Half or CN-PICO

It doesn't switch as often but MO told me where to go to specify a certain algo as I just wanted CN-PICO for some sites.

https://github.com/VidYen/webminerpool/commit/1500bf4da887517f7a31a9df010214e13b1b6f3a#diff-281ace1ded6364331406866c39b4e1cb

If you just want it to auto switch, then just use MO as your only pool as it already enabled ;)

**Comment by dx908** [comment]
@VidYen Thank you so much for quick response. Just another question. As I am using XMR Node Proxy as well. So in config I currently have set only one pool with xmr and cn/r setting.

So in case of auto Algo switch enabled, What should be the setting the config.json of xmr node proxy. For example here is default config of xmr node proxy

[https://github.com/dx908/xmr-node-proxy/blob/master/config_example.json](https://github.com/dx908/xmr-node-proxy/blob/master/config_example.json)
