### ISSUE TITLE
TLS issue with Mono on Ubuntu 15.x

### ISSUE THREAD

**Issue by Lancelight** [notgiven688/webminerpool#13]
As far as I am aware mono that ships with Ubuntu machines do not have support for TLS 1.1 or 1.2.  So the build fails on any distro that doesnt have a mono with TLS 1.1 or 1.2 support (which I dont think any version of mono has yet).  Therefore we need checks to see if TLS 1.1 or 1.2 support exists or it will fail here in: Fleck/WebSocketServer.cs around line 130ish

//Change the below
 EnabledSslProtocols = SslProtocols.Tls12 | SslProtocols.Tls11 | SslProtocols.Tls; 
to
EnabledSslProtocols = SslProtocols.Tls; // changed by wmp

I dont know who wmp is,  but it appears they likely ran into the same problem but then it was reverted for unknown reasons (likely during build on a windows system maybe where C# would have support for TLS?

Anyway,  a better way to handle this would be to check to see if Tls11 and 12 are even supported or not by checking to see which mono version is doing the build or perhaps just a check to see if it's MSVC doing the build or Mono and then once Mono has support,  change that check to see which version of Mono is doing the build.

This is the error you get if you attempt to build this project with Mono as instructed in the Readme:
/root/Documents/xmr/webminerpool/server/Server/Server.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

        Fleck/WebSocketServer.cs(133,42): error CS0117: `System.Security.Authentication.SslProtocols' does not contain a definition for `Tls12'

         0 Warning(s)
         1 Error(s)

Time Elapsed 00:00:00.7800490

**Comment by Lancelight** [comment]
Hmm well I just checked out mono's repo and it looks like TLS 1.2 was added as of 4.8.0,  so we need a check to look for 4.8.0 to fix this compile problem.

**Comment by Lancelight** [comment]
More on this is that I didnt know the MONO version was not available as a precompiler var.  So a Makefile is required to make this compile on any machine that does NOT have Mono 4.8.0 >.   Therefore a new entry in the README.md is needed that says this project is not compatible with anything less than Mono 4.8.0 and is NOT compatible with xbuild either,  the newer msbuild would have to be used.

Another option is to make a Makefile available that would add the Mono version so that the xbuild compiler can see and evaluate it.  That to me is the correct method.  Something like this would go in the Makefile and then README.md is changed to instruct users to run the makefile rather than the xbuild command directly.

Contents of Makefile would be:
export MONO_VERSION=`mono --version | grep version | cut -d " " -f 5`
xbuild Server.csproj

**Comment by notgiven688** [comment]
@Lancelight : Thank you for your posts. 
The wmp guy is me ;) (WebMinerPool). I will probably add a Makefile like you suggested.

**Comment by Lancelight** [comment]
O haha,  duuuuh. W..... M.... P.    Sometimes I can be pretty thick lol

**Comment by Lancelight** [comment]
Perhaps check to see if msbuild is even available first?  msbuild is something new for mono,  I dont have msbuild since I use ubuntu so I cant test to see if it works any differently.  You must be using a newer mono?  Maybe you installed it manually?

**Comment by notgiven688** [comment]
Msbuild is included in the latest version of mono.
I added a very simple bash-file which writes some comments and uses msbuild.
https://github.com/notgiven688/webminerpool/blob/verbose/server/build
