### ISSUE TITLE
UPDATE: cn-rwz support (GRAFT)

### ISSUE THREAD

**Issue by notgiven688** [notgiven688/webminerpool#131]
The master branch has been updated to include a new algorithm! This should improve your effective hashrate on pools like moneroocean.stream. Please Update.

**Comment by ianvm** [comment]
Thanks @notgiven688 
I updated : 
efd34e69-772b-4557-9df1-e3ea948ccd91: got job from pool (cn-rwz, v2)
b5bd7d7b-81a9-40ce-bcd3-e0b5b8e5b2c2: got job from pool (cn-rwz, v2)
7126722c-367a-4186-88b0-1c9b69e86136: got job from pool (cn-rwz, v2)
29e168f8-4765-4412-80cf-4d14427f089d: got job from pool (cn-rwz, v2)

Seems to work fine :)

**Comment by ianvm** [comment]
Can confirm it's working, it's been mining GRFT almost all the time on MoneroOcean since my update. 

Thanks once again for your great work! :)

**Comment by focaeppe** [comment]
Great update thank you @notgiven688, hope we will see other algo in futur
