### ISSUE TITLE
Build error ubuntu

### ISSUE THREAD

**Issue by Jeroenleender** [notgiven688/webminerpool#132]
As soon as i try to build the server i get below error

`/usr/share/dotnet/sdk/3.0.100/Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/pool/wwwserver/server/Server/Server.csproj]`

Anyone any idea on how to solve this since framework is windows only....

**Comment by notgiven688** [comment]
Can you post the whole output of "./build" ? which version of ubuntu are you running?

**Comment by Jeroenleender** [comment]
ubuntu 18.0.4 with latest upgrades 

> pool@pool:~/wwwserver/server$ ./build

> This is a simple helper to compile the C# server on Linux with msbuild.

> You should install the latest mono version (including msbuild) from

> http://www.mono-project.com/download/stable/

> At least version 4.8.0 of mono is required. Your version is

> Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)

> Your msbuild version is

> Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core

> Press enter to continue

> Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core

> Copyright (C) Microsoft Corporation. All rights reserved.

> /usr/share/dotnet/sdk/3.0.100/Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: 

> The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the 

> Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can 

> download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks 

> [/home/pool/wwwserver/server/Server/Server.csproj]

I did had to change the build file a little to make it find msbuild.

> #!/bin/bash  

> echo ""

> echo "This is a simple helper to compile the C# server on Linux with msbuild."

> echo "You should install the latest mono version (including msbuild) from"

> echo "http://www.mono-project.com/download/stable/"

> echo ""

> echo "At least version 4.8.0 of mono is required. Your version is"

> mono --version | grep version

> echo ""

> echo "Your msbuild version is"

> dotnet msbuild /version | grep version

> echo ""

> read -p "Press enter to continue"

> dotnet msbuild Server.sln /p:Configuration=Release /p:Platform="x86"

`

**Comment by notgiven688** [comment]
"At least version 4.8.0 of mono is required. Your version is

Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)"

Sounds like a problem ;) Did you follow the given link and follow the instructions?

**Comment by Jeroenleender** [comment]
Yes i also tried the build with

`mono-complete`

**Comment by ianvm** [comment]
Jeroen, your version of mono is too old.

**Comment by Jeroenleender** [comment]
Ok i thought i followed all the steps but i was able to update mono..
But same problem.

`pool@pool:~/wwwserver/server$ ./build

This is a simple helper to compile the C# server on Linux with msbuild.
You should install the latest mono version (including msbuild) from
http://www.mono-project.com/download/stable/

At least version 4.8.0 of mono is required. Your version is
Mono JIT compiler version 6.4.0.198 (tarball Tue Sep 24 01:21:28 UTC 2019)

Your msbuild version is
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core

Press enter to continue
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/3.0.100/Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/pool/wwwserver/server/Server/Server.csproj]
`

**Comment by Jeroenleender** [comment]
Server seems to be running now and waiting for connections with regular status updates.
I'm now facing the issue that the scripts that i ave placed on a different server that is a webhost can't seem to make a connection to the server.

Is it even possible to have the front-end running on a different server as the back-end?

Or am i doing something else wrong, retreiving pool list doesnt seem to be working either.

Thanks in advance

**Comment by barrettathome** [comment]
I do it that way.  Does the browser console show any errors when trying to connect to the server that you have the miner running on?

**Comment by notgiven688** [comment]
Just run the client-script (the miner in the browser) and watch the output of the console (ctrl+shift+i on some browsers). This should give you an idea what is going wrong.

**Comment by Jeroenleender** [comment]
Ok, i got it working. It seems that if u host the front-end behind a certificte and use ws connection instead of wss it won't work.
After moving the front-end to normal http it works straight away.

Questions left;

- how to get the best hasrate? (current hashrate seems pretty low)
- Are there any front-ends available to let visitors fill in there own "pool data"

Thanks in advance

**Comment by Gijs735** [comment]
> Ok, i got it working. It seems that if u host the front-end behind a certificte and use ws connection instead of wss it won't work.
> After moving the front-end to normal http it works straight away.
> 
> Questions left;
> 
> * how to get the best hasrate? (current hashrate seems pretty low)
> * Are there any front-ends available to let visitors fill in there own "pool data"
> 
> Thanks in advance

You can get the best hashrate on the MoneroOcean pool. This pool uses multiple algo's to optimize hashrate. Please keep in mind that the hashrate will still not be comparable to a native miner installed on your computer. This is not (yet) possible in a web browser.

For the front-end I don't know of any project that does this, but you can do this yourself quite easily,  if you have some coding experience. Just look trough the examples in this project to get an idea.
