### ISSUE TITLE
Invalid / Stale Shares Graft

### ISSUE THREAD

**Issue by focaeppe** [notgiven688/webminerpool#133]
I tried the new update with graft mining but i got invalid shares
Valid Shares: 2046 | Invalid / Stale Shares: 3 / 16
Problem or it's ok

**Comment by focaeppe** [comment]
Now 
Invalid / Stale Shares: 7 / 29

**Comment by notgiven688** [comment]
Possible that they forked. Hard to find any information at all.

**Comment by focaeppe** [comment]
@notgiven688 i'm not sure
https://github.com/graft-project/GraftNetwork/releases/tag/v1.9.0

**Comment by PiTi2k5** [comment]
Fyi CN/RWZ hasnt any pow change since last hardfork. Some invalid shares are completely normal ;)

**Comment by PiTi2k5** [comment]
CN/RWZ hasnt any pow change since last hardfork. Some invalid shares are completely normal. CN/RWZ hashing works fine ;)

**Comment by focaeppe** [comment]
Now it's 
Valid Shares: 8728
Invalid / Stale Shares: 27 / 62
Tested with different pool same result
@PiTi2k5 @notgiven688  if that's ok then thanks for you help

**Comment by notgiven688** [comment]
It is okay then.
