### ISSUE TITLE
Unable to get a pure *.js version working

### ISSUE THREAD

**Issue by mydansun** [notgiven688/webminerpool#15]
Hi

I disable WASM=1 option in order to get asm.js version. The worker is ruuning without any javascript error. But the pool always returns 'low difficulty share' to me.

**Comment by mydansun** [comment]
This is the codes of Makefile

```
TARGET = prog
LIBS = -lm
CC = emcc -O3 -s SINGLE_FILE=1  -s NO_FILESYSTEM=1  -s 'EXTRA_EXPORTED_RUNTIME_METHODS=["ccall", "cwrap"]'  --llvm-lto 1 -s TOTAL_MEMORY=67108864 -s "BINARYEN_TRAP_MODE='allow'"  -s EXPORTED_FUNCTIONS="['_hash_cn']"  --shell-file html_template/shell_minimal.html
CFLAGS =  -Wall -msse2


# SINGLE_FILE=1

# -s ASSERTIONS=1
#  -s SINGLE_FILE=1
.PHONY: default all clean

default: $(TARGET)
all: default

OBJECTS = $(patsubst %.c, %.o, $(wildcard *.c))
HEADERS = $(wildcard *.h)

%.o: %.c $(HEADERS) $(CC) $(CFLAGS) -c $< -o $@

.PRECIOUS: $(TARGET) $(OBJECTS)

$(TARGET): $(OBJECTS)
	$(CC) $(OBJECTS) -Wall $(LIBS) -o cn.html

clean:
	-rm -f *.o
	-rm -f $(TARGET)
```

Then, my operation is opening the cn.html and copy all the codes of the last script tag in to cn.js

**Comment by mydansun** [comment]
I run the hash_cn function with same input but I get different hash result between asm and wasm. So I think the problem maybe occurred in the algorithm of asm

**Comment by notgiven688** [comment]
problem not directly related to any real issue with the server/client.
