### ISSUE TITLE
STELLITE (XTL) Fork CryptoNightV7

### ISSUE THREAD

**Issue by patrickbau** [notgiven688/webminerpool#16]
Hello,
STELLITE algo now is V7 
Is this project Compatible  ?

**Comment by notgiven688** [comment]
Who is STELLITE?

**Comment by patrickbau** [comment]
https://stellite.cash/
https://coinmarketcap.com/currencies/stellite/
Good project and it's the most profitable for the moment

**Comment by notgiven688** [comment]
If it is cnv7 then it is compatible.

**Comment by patrickbau** [comment]
Yes it's cnv7 
I tried ,but it's not working

**Comment by notgiven688** [comment]
More details! :) Did you add a XTL pool to the server?

**Comment by patrickbau** [comment]
The error
![2018-04-10_21-17-32](https://user-images.githubusercontent.com/34626734/38578652-cfca7844-3d04-11e8-805e-830d204b13d8.jpg)

**Comment by notgiven688** [comment]
You do not even get a connection.

PoolPool.Add("communitypool.stellite.cash",new PoolInfo("communitypool.stellite.cash",	6655,"x"));

works for me.

**Comment by patrickbau** [comment]
Yes i was my mistake
But sorry i think it's not compatible 
( got a pool rejection )

**Comment by notgiven688** [comment]
It is probably compatible if you are willing to change some lines in the webassembly code.
Remove this line https://github.com/notgiven688/webminerpool/blob/9201b77a1e24b2dadbcfa088f851a689288c25f2/hash_cn/webassembly/xmr/cryptonight.c#L372

and uncomment the next one.
