### ISSUE TITLE
websocket not reachable after some time [windows server]

### ISSUE THREAD

**Issue by PiTi2k5** [notgiven688/webminerpool#17]
Hello notgiven688,

i use Windows Server 2016 and the websocket port is not reachable after some running time.

Fleck warn:
System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.IO.IOException: Von der ?bertragungsverbindung k?nnen keine Daten gelesen werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. ---> System.Net.Sockets.SocketException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
   bei System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   bei System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- Ende der internen Ausnahmestapel?berwachung ---
   bei System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   bei System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   bei System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   bei System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- Ende der internen Ausnahmestapel?berwachung ---

Fleck error:
System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.IO.IOException: Von der ?bertragungsverbindung k?nnen keine Daten gelesen werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. ---> System.Net.Sockets.SocketException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
   bei System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   bei System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   --- Ende der internen Ausnahmestapel?berwachung ---
   bei System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   bei System.Net.FixedSizeReader.StartReading()
   bei System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   bei System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   bei System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   bei System.Net.Security.SslStream.BeginAuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   bei Fleck.SocketWrapper.<>c__DisplayClass10_0.<Authenticate>b__0(AsyncCallback cb, Object s)
   bei System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   bei Fleck.SocketWrapper.Authenticate(X509Certificate2 certificate, SslProtocols enabledSslProtocols, Action callback, Action`1 error)
   bei Fleck.WebSocketServer.OnClientConnect(ISocket clientSocket)
   bei Fleck.SocketWrapper.<>c__DisplayClass23_0.<Accept>b__1(Task`1 t)
   bei System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapel?berwachung ---
---> (Interne Ausnahme #0) System.IO.IOException: Von der ?bertragungsverbindung k?nnen keine Daten gelesen werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. ---> System.Net.Sockets.SocketException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
   bei System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   bei System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   --- Ende der internen Ausnahmestapel?berwachung ---
   bei System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   bei System.Net.FixedSizeReader.StartReading()
   bei System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   bei System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   bei System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   bei System.Net.Security.SslStream.BeginAuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   bei Fleck.SocketWrapper.<>c__DisplayClass10_0.<Authenticate>b__0(AsyncCallback cb, Object s)
   bei System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   bei Fleck.SocketWrapper.Authenticate(X509Certificate2 certificate, SslProtocols enabledSslProtocols, Action callback, Action`1 error)
   bei Fleck.WebSocketServer.OnClientConnect(ISocket clientSocket)
   bei Fleck.SocketWrapper.<>c__DisplayClass23_0.<Accept>b__1(Task`1 t)
   bei System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()<---

**Comment by PiTi2k5** [comment]
I have a lot of the same messages on the fleck txt files. It is a random time when websocket not response/reachable. I need to delete all files except server.exe and than the websocket is reachable after app restart. You can add me via skype piti2k5 for more detail logs.

**Comment by PiTi2k5** [comment]
I will try add more websocket ports/server app. I have constant 25-30k miners connected and that can caused a eye of a needle, so i can split the work.

**Comment by PiTi2k5** [comment]
Yesterday the server.exe is crashed two times.

Anwendung: server.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.Net.Sockets.SocketException
   bei System.Net.Sockets.Socket.DoBind(System.Net.EndPoint, System.Net.SocketAddress)
   bei System.Net.Sockets.Socket.Bind(System.Net.EndPoint)
   bei Fleck.SocketWrapper.Bind(System.Net.EndPoint)
   bei Fleck.WebSocketServer.Start(System.Action`1<Fleck.IWebSocketConnection>)
   bei Server.MainClass.Main(System.String[])
--------------------------------------------------
Name der fehlerhaften Anwendung: server.exe, Version: 1.0.6674.25485, Zeitstempel: 0x5acca97b
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.14393.2155, Zeitstempel: 0x5a9e2470
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000daa12
ID des fehlerhaften Prozesses: 0xb980
Startzeit der fehlerhaften Anwendung: 0x01d3d1c937108072
Pfad der fehlerhaften Anwendung: C:\Users\xxxx\Desktop\server.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 4a7a4875-befd-4ad7-90bc-a0ec043977f2
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by PiTi2k5** [comment]
Issue closed for now, until more tests. Added 3 more websockets for load balancing.

**Comment by notgiven688** [comment]
could be connected to: https://github.com/statianzo/Fleck/issues/207
also windows server.

**Comment by PiTi2k5** [comment]
Partially fixed with more load balancing (more physical servers & websockets added) and some more try/catch. On peaks i see over 43k miners online in my monitor system. I think for constant 10k miners online you need 1 websocket per server because of connection limitations --> to much delay and new users cant connect. I speak for Windows Server ;)

**Comment by PiTi2k5** [comment]
Switched to ListenerSocket.Listen(100); // changed from 1000 on WebSocketServer.cs it runs much better without issue websocket not reachable after some time.
Last issue i need to fix is, random crash after some hours, temp. fix is a watchdog programm that restart the crashed app

Anwendung: server.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.NullReferenceException
   bei Server.PoolConnectionFactory.ReceiveCallback(System.IAsyncResult)
   bei System.Net.LazyAsyncResult.Complete(IntPtr)
   bei System.Net.ContextAwareResult.CompleteCallback(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   bei System.Net.ContextAwareResult.Complete(IntPtr)
   bei System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
   bei System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   bei System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

**Comment by notgiven688** [comment]
If this was really the cause: Great catch! I will carefully read the documentation about the listener backlog (again)  and fix it. Probably some system resource was exhausted with <40k connections and this backlog size.

**Comment by PiTi2k5** [comment]
And a big thank you to you for the great help/support via skype.

**Comment by notgiven688** [comment]
https://github.com/notgiven688/webminerpool/commit/956fec61c9cd76e735dd80a547d637ff8d77a775
