### ISSUE TITLE
how can I get this to work with my own pool?

### ISSUE THREAD

**Issue by hypeboard** [notgiven688/webminerpool#2]
I would like to use this to offer my users a way to web mine on my pool

**Comment by notgiven688** [comment]
If you run your own server you can just add your pool in Program.cs: https://github.com/notgiven688/webminerpool/blob/bb753cedfe20175af95d8d8c348c77cb65d552bc/server/Server/Program.cs#L179

If you want you pool added to the webminerpool.com server you either add the configuration-line to Program.cs and do a pull request or you simply ask me to do it for you.

**Comment by hypeboard** [comment]
Awesome! Thanks for the quick reply. I will just do a pull request so you
can add it at your convenience. If that is not your preferred method just
let me know.

**Comment by notgiven688** [comment]
No problem. Will be done within the next 6h.
