### ISSUE TITLE
hashlib.so is not available

### ISSUE THREAD

**Issue by ecSpl01t** [notgiven688/webminerpool#20]
Hi,
Could you explain, how to fix that: hashlib.so is not available. Checking user submitted hashes disabled. ?

Because I don't understand this:
"The monero/aeon cryptonight hashing functions in C code. With simple Makefiles for use with gcc and emcc - the emscripten webassembly compiler. libhash should be compiled so that the server can check hashes calculated by the user."

**Comment by notgiven688** [comment]
If you are under linux a simple "make" in webminerpool/hash_cn/libhash/ should create hashlib.so - which you should copy to the same directory.

**Comment by ecSpl01t** [comment]
I don't have that file, when I run second time i've this:
$ make
gcc -O3 -shared -fPIC  hash-extra-groestl.o  aesb.o  blake256.o  jh.o  crypto-ops.o  main.o  hash.o  groestl.o  oaes_lib.o  random.o  tree-hash.o  hash-extra-jh.o  chacha.o  hash-extra-blake.o  crypto-ops-data.o  hash-extra-skein.o  keccak.o  skein.o  slow-hash.o -Wall -lm -o libhash.so

**Comment by notgiven688** [comment]
You have to build libhash.so.

"If you are under linux a simple "make" in webminerpool/hash_cn/libhash/ should create hashlib.so - which you should copy to the server directory."

**Comment by notgiven688** [comment]
the process "mono server.exe" has to find libhash.so - so put it into the local directory where you are starting server.exe from.

**Comment by ecSpl01t** [comment]
Thank you!

**Comment by notgiven688** [comment]
You are welcome. I close this issue :)
