### ISSUE TITLE
WebSocketConnection. Not able to perform handshake within 20s.

### ISSUE THREAD

**Issue by ecSpl01t** [notgiven688/webminerpool#21]
Hi,
Could you explain what does it mean ?

**Comment by notgiven688** [comment]
Closes a websocketconnection which is in a limbo state. Most likely caused by a connection interrupt. You should not see too many of these.

**Comment by PiTi2k5** [comment]
@ecSpl01t I see that messages when i start the .exe with a externally programm like a watchdog program. What do you use? Linux or Windows?

**Comment by ecSpl01t** [comment]
@PiTi2k5, Linux

**Comment by ecSpl01t** [comment]
I've each 6-10 sec that message.

**Comment by notgiven688** [comment]
It is just a failed connection - not an issue.
