### ISSUE TITLE
Is there some obfuscation?

### ISSUE THREAD

**Issue by slayerulan** [notgiven688/webminerpool#23]
Hello,
I integrated it to xmr-node-proxy's websocket but it sends different hashes for same job again and again. Is there any obfuscation on server -libhash-?

if so, how can we integrate it to MoneroOcean/cryptonight-hashing? I can offer bounty for this + coinhive-style FORCE_EXCLUSIVE_TAB solution

Thanks

**Comment by notgiven688** [comment]
> I integrated it to xmr-node-proxy's websocket but it sends different hashes for same job again and again

That is okay. There are multiple solutions (nonce values) for the same job.

I do not understand your other questions.

**Comment by slayerulan** [comment]
@notgiven688 but is it normal to send 20+ different nonces for same job (which has low difficultly because of xmr-node-proxy's nature) like an infinite loop? /:

**Comment by notgiven688** [comment]
Yes. completely normal. A higher difficulty should be better, because it would decrease the traffic.
