### ISSUE TITLE
xmrig-proxy support

### ISSUE THREAD

**Issue by alebeta90** [notgiven688/webminerpool#25]
Hello,

by any chance is possible to make it work with xmrig-proxy ?

thanks

**Comment by notgiven688** [comment]
Why do you need it? What does it do?

**Comment by alebeta90** [comment]
Hello @notgiven688 ,
It is because I can set a name instead of a wallet, with the name of the user/website. Then from xmrig proxy i can check the stats for each user/website easily using api call. Normally xmrig-proxy needs an --nicehash option to be set on the miner. But im doing a test with a similar proxy xmr node proxy, it may work with that. 

also with proxy you can do change on the proxy level, about the pool and wallet address to use, it is easier.

Thanks for all your help

**Comment by alebeta90** [comment]
I saw in the issue #23 this friend is using this proxy and it is for the same reason I can bet. 

There is on mind any implementation for sumokoin? Actually mining superiorcoin and works perfectly

**Comment by alebeta90** [comment]
Using xmr node proxy is enough, thanks for all the support!
