### ISSUE TITLE
Error Listener socket

### ISSUE THREAD

**Issue by patrickbau** [notgiven688/webminerpool#26]
Hello,
Is that a problem when it's too many errors
FLECK: Server started at ws://0.0.0.0:8282 (actual port 8282)
FLECK: Listener socket restarted
FLECK: Listener socket is closed One or more errors occurred.
FLECK: Listener socket restarting
FLECK: Server started at ws://0.0.0.0:8282 (actual port 8282)
FLECK: Listener socket restarted
FLECK: Listener socket is closed One or more errors occurred.
FLECK: Listener socket restarting
FLECK: Server started at ws://0.0.0.0:8282 (actual port 8282)
FLECK: Listener socket restarted
FLECK: Listener socket is closed One or more errors occurred.
FLECK: Listener socket restarting
FLECK: Server started at ws://0.0.0.0:8282 (actual port 8282)
FLECK: Listener socket restarted
FLECK: Listener socket is closed One or more errors occurred.
FLECK: Listener socket restarting
FLECK: Server started at ws://0.0.0.0:8282 (actual port 8282)
FLECK: Listener socket restarted
FLECK: Listener socket is closed One or more errors occurred.
FLECK: Listener socket restarting
FLECK: Server started at ws://0.0.0.0:8282 (actual port 8282)
FLECK: Listener socket restarted
FLECK: Listener socket is closed One or more errors occurred.
FLECK: Listener socket restarting
FLECK: Server started at ws://0.0.0.0:8282 (actual port 8282)
FLECK: Listener socket restarted
FLECK: Listener socket is closed One or more errors occurred.
FLECK: Listener socket restarting
FLECK: Server started at ws://0.0.0.0:8282 (actual port 8282)
FLECK: Listener socket restarted
FLECK: Listener socket is closed One or more errors occurred.
FLECK: Listener socket restarting
FLECK: Server started at ws://0.0.0.0:8282 (actual port 8282)
FLECK: Listener socket restarted
FLECK: Listener socket is closed One or more errors occurred.
FLECK: Listener socket restarting
FLECK: Server started at ws://0.0.0.0:8282 (actual port 8282)
FLECK: Listener socket restarted
FLECK: Listener socket is closed One or more errors occurred.
FLECK: Listener socket restarting
FLECK: Server started at ws://0.0.0.0:8282 (actual port 8282)
FLECK: Listener socket restarted
FLECK: Listener socket is closed One or more errors occurred.
FLECK: Listener socket restarting

**Comment by notgiven688** [comment]
I will just ignore you sigabrt error in the following:

"FLECK: Server started at ws://0.0.0.0:8282 (actual port 8282)
FLECK: Listener socket restarted"

That is not healty. The server can not listen on that port. Try another port for debugging purposes.

**Comment by ianvm** [comment]
Tbh, I have the same issue. Still seems to work fine though. I'll try to dig into it when I have more time.

**Comment by patrickbau** [comment]
Yes the error is just with : FLECK: Listener socket restarting
Just changed the port  and i will see the result soon

**Comment by patrickbau** [comment]
1006 connections maximum

**Comment by patrickbau** [comment]
Great thanks notgiven688 problem solved

**Comment by GustavoEdny** [comment]
I have same problem when the server reached 1000 connections, I search about this, but i dont find a response for this problem. What is the solution and what is the best configuration for this project?

**Comment by letlet** [comment]
@GustavoEdny Your problem has already been mentioned in the Readme:

Attention: Most linux based systems have a (low) fixed limit of available file-descriptors configured ("ulimit"). This can cause an unwanted upper limit for the users who can connect (typical 1000). You should change this limit if you want to have more connections.
