### ISSUE TITLE
Feature request, Support for Stellite and Turtlecoin

### ISSUE THREAD

**Issue by PiTi2k5** [notgiven688/webminerpool#28]
Support for Turtlecoin Cryptonight-Lite V1 (they forked from cryptonight to cryptonight-lite variant)
Support for Stellite (they forked to Cryptonight V1, same as Monero V7, but with Blockversion V3)
Support for Sumokoin (they forked to Cryptonight-Heavy)

After all these custom forks, I'm just confused :D

**Comment by patrickbau** [comment]
You should also add Graft coin they just forked to CryptoNightV7 as Monero
For Stellite [https://github.com/notgiven688/webminerpool/issues/16](url) Tested work perfect
Sumokoin (Cryptonight-Heavy) is not for webminig anymore, with this algo you get less hash rat for 50% then other coins, mining through web is waste of time
Turtlecoin : I don't know
Graft: (CryptoNightV7) i think it's work but i didn't have time to test it
now we are waiting for Electroneum they will fork to CryptoNightV7 as Monero maybe the last of this month or the next

**Comment by notgiven688** [comment]
-> Turtlecoin should nearly work with the AEON miner, since they are both cn lite. Does someone want to test?

**Comment by PiTi2k5** [comment]
Graft is working fine on new fork. So when stellite need a edit on variant, so turtlecoin needs too. Because on standard cryptonight-lite wasm turtlecoin get always share rejects. I have tested all good cryptonight coins, they can mined fine. 
Except: Stellite, Intensecoin, Turtlecoin and Sumokoin ---> Intensecoin has forked to Cryptonight V1 Blockversion 4 i think same game as Stellite :P

**Comment by notgiven688** [comment]
@PiTi2k5 @patrickbau I will implement a recent stratum extension which allows us to set the cn_version explicitly - probably this weekend. That should allow us to mine cn and cn_lite coins with different versions.

**Comment by patrickbau** [comment]
@notgiven688 That's will be great, can't wait to see this new version
Thank you :smile:

**Comment by PiTi2k5** [comment]
@notgiven688 Thanks :) I have tested Intensecoin/Stellite and Turtlecoin with cryptonight-lite #16 tip it works fine

**Comment by notgiven688** [comment]
@PiTi2k5 @patrickbau Good news. Everything is implemented. Cryptonight/Cryptonight supported in all its variants by implementing https://github.com/xmrig/xmrig-proxy/blob/dev/doc/STRATUM_EXT.md#mining-algorithm-negotiation . Default algo/variant combinations are specified when adding the pool. Example:

Aeon-pool: PoolPool.Add ("aeon-pool.com", new PoolInfo ("mine.aeon-pool.com", 5555, "", "cn-lite", -1));
(use cn-lite and use auto-detect which makes us fork-ready)

Turtle-pool: PoolPool.Add ("slowandsteady.fun", new PoolInfo ("slowandsteady.fun", 3333, "", "cn-lite", 1));
(use cn-lite in variant 1)

**Comment by patrickbau** [comment]
Great thanks @notgiven688 work perfect
