### ISSUE TITLE
3% fee

### ISSUE THREAD

**Issue by develth** [notgiven688/webminerpool#29]
Hi there,

first - thanks for your code & the project you share!

I stumpled upon Program.cs
    
        // by default a 3% dev fee is submitted to the following address.
        // thank you for leaving this in.

Does that mean that you get a 3% fee for using this tool? 
If you do that this way, you should mention that in the Readme.md to ensure transparency and gives you trust. 
If not, i would be happy about a little clarification. 

Thanks in advance & cheers,
Thomas

**Comment by echel0n** [comment]
Yes please explain and perhaps make connecting to the dev pool optional by
using a define during build

**Comment by notgiven688** [comment]
It says right when you start the server "dev fee of 3% enabled". I will add something to the readme.

**Comment by echel0n** [comment]
Could you add a define so we can either disable this all together or set
the fee during builds ?

**Comment by notgiven688** [comment]
Yes.

**Comment by notgiven688** [comment]
https://github.com/notgiven688/webminerpool/commit/9baec80163fd93a19035e71fb23cd2aaf6c9c42a

**Comment by develth** [comment]
Thanks for the quick information & change!

**Comment by echel0n** [comment]
I don't see where I can disable this via a build define ?

**Comment by develth** [comment]
@echel0n DevDonation.cs

**Comment by develth** [comment]
But feel free to make a PR and submit a suggestion to discuss about
