### ISSUE TITLE
Network problem. Freeze

### ISSUE THREAD

**Issue by MaximKiselev** [notgiven688/webminerpool#30]
hi, i found some problem.
server will be freeze after some work.
websocket has pending status. not 101.
on backend i found also 
`Fleck Application error socket was not closed`
but i did not see error line, maybe add debug mode arg.
server is periodically freezes. time -3-6 hours of work. libhash disabled. version - git latest.
thanks

**Comment by notgiven688** [comment]
Windows?

**Comment by Mila432** [comment]
hmm cant confirm , have 40k open connections

**Comment by notgiven688** [comment]
@Mila432 Sorry to bother you - just want to be sure: *Can* confirm or *Can not* confirm?

@MaximKiselev How many connections do you have?
