### ISSUE TITLE
Jobqueue VS Speed Total

### ISSUE THREAD

**Issue by GustavoEdny** [notgiven688/webminerpool#32]
I can see this in server logs: 

Jobqueue: 80.2k; speed total: 10.56kH/s
Jobqueue: 40.2k; speed total: 35.15kH/s

The speed total do not reflect the real speed that can be see in my pool. What is the real function for Jobqueue? This is a problem?

**Comment by notgiven688** [comment]
The jobqueue just remembers alls jobs it sends out to clients and forgets about old ones. The commication looks like this: server: here is job xyz100, client (after a while): I finally solved xyz100.. the server then looks up xyz100 in the queue and performs some checks.

Speed total is just an estimation of the hashpower. It can fluctuate and this is okay. You can average over larger times and it should give you a good value.
