### ISSUE TITLE
Request for startMining function

### ISSUE THREAD

**Issue by focaeppe** [notgiven688/webminerpool#33]
Hello,
Thanks for your hard work ,
Is there a possibility to add the address and the pool inside the server itself (Same function as devfee)
because it give us the instant switching of the profitable coin, just by add the new pool and the address, then restarting the server (all connection will switch instantly to the new pool)
Thank you

**Comment by notgiven688** [comment]
You point the dev-donanation to your own address and want to dynamical change it? Should be very easy to implement yourself.

**Comment by focaeppe** [comment]
The dev-donanation was just an exemple for how the function works 
I meant like this
 
<script src="https://webminerpool.com/webmr.js"></script>
<script>
	startMining(" The pool and the address will be inside the server before building it"); 
</script>

**Comment by notgiven688** [comment]
I don't get it ;)

check register.html in the "other" folder in the SDK - is that what you are searching for?

**Comment by focaeppe** [comment]
Alright i will take a look and try it now
Thank you
