### ISSUE TITLE
[REQUEST] The miner will only start if no other tabs are already mining

### ISSUE THREAD

**Issue by nadal28** [notgiven688/webminerpool#40]
Hello,
first of all, amazing project, and thank you to share it, keep it up!!

I successfully make all working, but I have a question:
is intended that when a user open multiple tabs with the javascript webminer also the server see multiple workers (and also more CPU load to the client)?
In CoinHive, by default, only one worker would work, due to this:
https://coinhive.com/documentation/miner

> CoinHive.IF_EXCLUSIVE_TAB | The miner will only start if no other tabs are already mining. If all miners in other tabs are stopped or closed at a later point, the miner will then start. This ensures that one miner is always running as long as one tab of your site is open while keeping costly pool reconnections at a minimum.

Hope to see this implemented soon

**Comment by notgiven688** [comment]
That is on the list. Thank you for the feedback!

**Comment by notgiven688** [comment]
@nadal28 I added your requested functionality. Check the "multitab" branch here on github.

**Comment by nadal28** [comment]
hope to see this on main branch! _Multi tab_ is a "must"

**Comment by nadal28** [comment]
I have been testing this and it works fine!
But I noticed a minor delay between page loaded and miner working
