### ISSUE TITLE
Heavy Memory load-1.9G memory usage with 30 clients.

### ISSUE THREAD

**Issue by letlet** [notgiven688/webminerpool#42]
This is log from systemctl status:

webminepool.service - webminepool
   Loaded: loaded (/etc/systemd/system/webminepool.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-05-15 14:07:42 CST; 23h ago
 Main PID: 32101 (mono)
    Tasks: 27
   Memory: 1.9G
      CPU: 2min 5.597s
............................
May 16 13:42:19 ubuntu mono[32101]: 288cfc97-1f09-4c55-899d-0f821e585b53: got job from pool
May 16 13:42:19 ubuntu mono[32101]: Connecting: 127.0.0.1
May 16 13:42:19 ubuntu mono[32101]: 2cf1c3d3-e122-43f8-bb9d-ad27548928d8: connected with ip 127.0.0.1
May 16 13:42:19 ubuntu mono[32101]: 2cf1c3d3-e122-43f8-bb9d-ad27548928d8: handshake - aeon-pool.com, Wmsng3CK...
May 16 13:42:19 ubuntu mono[32101]: 2cf1c3d3-e122-43f8-bb9d-ad27548928d8: reusing pool connection
May 16 13:42:19 ubuntu mono[32101]: 2cf1c3d3-e122-43f8-bb9d-ad27548928d8: got job from pool
May 16 13:42:24 ubuntu mono[32101]: [5/16/2018 1:42:24 PM] heartbeat; connections client/pool: 30/2; jobqueue: 34.3k; speed: 0.8kH/s
May 16 13:42:25 ubuntu mono[32101]: b7994290-09fc-4f04-a50d-d900f1bfcc5c: reports solved hash
May 16 13:42:25 ubuntu mono[32101]: b7994290-09fc-4f04-a50d-d900f1bfcc5c: got hash-checked
May 16 13:42:25 ubuntu mono[32101]: b7994290-09fc-4f04-a50d-d900f1bfcc5c: solved job
............................
May 16 13:46:14 ubuntu mono[32101]: [5/16/2018 1:46:14 PM] heartbeat; connections client/pool: 25/2; jobqueue: 34.3k; speed: 1.2kH/s
....................................

My server: ubuntu16.04 , run webminerpool behind nginx
Any suggestion would be appreciated！

**Comment by letlet** [comment]
Memory usage still growing even no new client. Maybe this problem is with jobqueue? 
 Active: active (running) since Tue 2018-05-15 14:07:42 CST; 1 day 18h ago
 Main PID: 32101 (mono)
    Tasks: 17
   Memory: 3.0G
      CPU: 3min 56.442s
May 17 08:44:19 ubuntu mono[32101]: [5/17/2018 8:44:19 AM] heartbeat; connections client/pool: 9/2; jobqueue: 62.1k; speed: 0.7kH/s

**Comment by Mila432** [comment]
i think so , it eats 29gb ram on my server
but i also have more connections

**Comment by letlet** [comment]
29Gb is a huge number, I used to have another proxy(before CN v7) made by golang which can host over 20K clients with less than 1Gb memory usage.
Must be memory leak some where with this proxy.

**Comment by notgiven688** [comment]
Hui.. never had this problem. 40k connections - 2 gbyte.

**Comment by nadal28** [comment]
40k? are you rich ? xD @notgiven688

**Comment by notgiven688** [comment]
This was on the test-servers. Where I tried to take a fee which perfectly pays the server costs - so no ;)

you use ubuntu 16.04? which version of mono?

**Comment by notgiven688** [comment]
I will implement a dynamic Jobq. soon. At the moment it is limited to 100k entries. To test if it has any effect modify the line

public const int JobCacheSize = (int) 1e5;

in Program.cs. Try 

public const int JobCacheSize = (int) 100;

**Comment by nadal28** [comment]
is not "good" to use a web server proxy?? Im using an apache proxy just to use the SSL cert of my domain

**Comment by notgiven688** [comment]
@nadal28 You can do that. But it should be much more efficient to directly connect the server with your clients.

**Comment by letlet** [comment]
@notgiven688 Yes, I use the nginx as proxy server because I need the 443 port for some other websites in the same server. And yes it's Ubuntu 16.04. 
Here is the mono on my server:

Mono JIT compiler version 5.12.0.226 (tarball Thu May  3 09:48:32 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)


Today the jobqueue reached 100.0k and it cost 5.3G , I will report the momory usage after a while to see if jobqueue's size connected with huge memory

**Comment by letlet** [comment]
Still 5.3Gb memory usage with 100.0k jobqueue after 2 days. So the problem should be the jobqueue.
I have no more than 30 clients concurrent running, why so large jobqueue?

**Comment by notgiven688** [comment]
@letlet That is good news. Just set a lower value. I will be a dynamic value in the new releases. Thank you for testing.

**Comment by letlet** [comment]
@notgiven688 Thank u for your excellent job, I will test the new version when released and feedback here.

**Comment by Mila432** [comment]
restarted proxy 2 days ago and here now
![image](https://image.prntscr.com/image/XKDvC6htR6W6CXvvNK_j2Q.png)

**Comment by brainscar** [comment]
@letlet what is your memory usage now?

**Comment by letlet** [comment]
@brainscar No improvement now.

**Comment by letlet** [comment]
I have upgraded mono to:
Mono JIT compiler version 5.12.0.301 
and webminerpool server cost about 650M memory with about 1000 clients after 16 hours's running.
I upgraded some other packages too(with apt upgrade).
So, maybe it's mono's problem or even the local enviroment's problem?
I'll continue investigate and update here.

**Comment by notgiven688** [comment]
@letlet Thank you for your tests/reports. I need some brave men, since I can not reproduce this stupid memory problem... @everyone: feel free to write about your memory consumption here.

**Comment by letlet** [comment]
webminerpool has runned stably for  last 8 days and cost about 3.5G memory with 1000 clients since day 2.

Then it cost 5.0G memory with 1000 clients after a restart 12 hours ago.

I will try another server soon later to verify it this connected with the server's env.

**Comment by notgiven688** [comment]
@letlet This is too much. 1000 clients should use less than 1gb. Maybe you can try to run the docker file..

**Comment by marcelobcortes** [comment]
having such massive amount of workers in a single server is a reliable choice?
well if i get constantly 40k workers i'd for sure spin up a pool
but i wonder if some minor or major issues could happen in this single server architecture that could make me cry

can you tell me your server specs and estimated bandwidth in that 40k situation?

**Comment by develth** [comment]
I have about 4 users and it always grows pretty fast to 3G. Have to restart it almost every two days

**Comment by nox956** [comment]
In my case, disable hash check (libhash.so) solve high mem usage problem.

**Comment by develth** [comment]
thanks for the hint, @nox956 
I removed the libhash.so from one of the two servers, so i can compare if it will change the memory consumption

**Comment by notgiven688** [comment]
@develth Result would be very interesting because it indicates a memory leak in libhash. It was rewritten for cn_v2 anyway, but I am curious.

**Comment by develth** [comment]
Currently both have a memory consumption of 70%

**Comment by develth** [comment]
Today i got a mail from my monitoring. 
currently server.exe uses 80% of 4GB RAM

**Comment by develth** [comment]
Now at 90%, still only 2 Clients

**Comment by develth** [comment]
With the latest update, the RAM usage on both server is pretty awesome.
No increase - all as it should. 
Thanks

**Comment by notgiven688** [comment]
@develth Latest update = latest system update? Or latest update of webminerpool?

Thanks for reporting - as always :)

**Comment by develth** [comment]
Latest webminerpool update
