### ISSUE TITLE
Anti-detection protector

### ISSUE THREAD

**Issue by MaximKiselev** [notgiven688/webminerpool#43]
hi, webmr.js some av detect it as trojan.miner. can u advice me good builder for bypass?

**Comment by letlet** [comment]
obfuscate the webmr.js may help with your problem.

**Comment by MaximKiselev** [comment]
@letlet  ok, thanks. i already did it, but script also was detected. maybe there is universal solution for bypass adblock/av and etc without change host or dinamically regen script...because script was place on own white site

**Comment by nadal28** [comment]
where do you check if the script is detectable? @MaximKiselev

**Comment by MaximKiselev** [comment]
@nadal28 i check via av k4sp3r$ky, it has web scaner. also adblock will block script if not use it on own source host....  I think it's problem of all web miner, but solution create multiple source hosts and check object js of miner  is temporary solution.

**Comment by letlet** [comment]
Modify all the global variables's name and dynamic regenerate the js files  then obfuscate it should work(you can do it automatically with some python script).

I have done this before with coinhive's js files and it worked, no any adblock or anti-virus software can detect it

**Comment by nadal28** [comment]
@MaximKiselev 
Also, I suggest you to inform users that you are using a miner, is not ethical otherwise.
Maybe let them choose between ads or the miner, and throttle it correctly

**Comment by letlet** [comment]
@nadal28 that's true, tell the user and get their permission is important and u can even give the user some bonus after mine for a while

**Comment by nadal28** [comment]
@letlet I've obfuscate the code, change variables and that... But k4$p3r$ky keep detecting the javascript :S

**Comment by paul0921** [comment]
Maybe load the script but wait 10 or 15 seconds before calling startMining?

**Comment by nadal28** [comment]
Are you guys by-passing heuristic?
