### ISSUE TITLE
webminerpool.com horizontal scaling, check out https://minexmr.stream

### ISSUE THREAD

**Issue by paul0921** [notgiven688/webminerpool#44]
I revamped the old webminerpool.com at [minexmr.stream](https://minexmr.stream).This server is running on AWS and should automatically scale (launch more instances of the VM) when necessary. Still need to work on the formula for the percentage cut, and a clear documentation for how to install web mining.

**Comment by cRYPT0-z** [comment]
Will you announce the percentage cut ahead of time? Or will it just suddenly be applied?

**Comment by brainscar** [comment]
Thank you @paul0921

**Comment by paul0921** [comment]
@brainscar I just got hit with a wave of 3000 users. Is that you?

**Comment by brainscar** [comment]
@paul0921 no not me, was just checking out your project and could appreciate the effort. Haven't tried it yet.

**Comment by brainscar** [comment]
@paul0921 you might want to post this in the new public servers thread.
