### ISSUE TITLE
[QUESTION] Best pool port? The one with lowest difficulty (webmining)

### ISSUE THREAD

**Issue by nadal28** [notgiven688/webminerpool#45]
After read this: https://www.reddit.com/r/Monero/comments/7kf59l/test_results_pool_difficulty_vs_javascript_web/
Maybe pools.json should be tweaked

**Comment by notgiven688** [comment]
The easiest port was chosen for pools.json. Feel free to change it.

Math tells us, that is does not matter in the long run - Closed.

**Comment by letlet** [comment]
According to my experience I agree with notgiven688. low diff (100),high diff(10000) turns out same hashrate after run for a while. And high diff even decrease the risk of being banned by pool.
