### ISSUE TITLE
[QUESTION] How to properly reduce Client CPU load

### ISSUE THREAD

**Issue by nadal28** [notgiven688/webminerpool#47]
I currently have 95/100 Throttle, if I run the script over Google Chrome I get 17~ CPU usage; But also Im getting with 20 clients around 50h/s
To achieve this the only way is to set a higher throttle? Is there other way to not overload client CPU and get more of hashes per second?

**Comment by gromatl** [comment]
Hi nadal,
For reduce cpu load you should set the amount of CPU used in client manually. Depends on device its better over time to use 1 cpu and a Throttle to 0-5.
