### ISSUE TITLE
Listener socket is closed

### ISSUE THREAD

**Issue by wonchoe** [notgiven688/webminerpool#48]
Any idea? 

> FLECK: Error while listening for new clients One or more errors occurred.
> FLECK: Listener socket restarting
> FLECK: Server started at ws://0.0.0.0:8181 (actual port 8181)
> FLECK: Listener socket restarted
> FLECK: Error while listening for new clients One or more errors occurred.
> FLECK: Listener socket restarting
> FLECK: Server started at ws://0.0.0.0:8181 (actual port 8181)
> FLECK: Listener socket restarted
> Closing/Disposing WebSocketConnection. Not able to perform handshake within 20s.
> Connecting: 87.120.216.243
> 5957da8d-5087-4262-b0c8-bca0d2cb8fdb: connected with ip 87.120.216.243
> Warning: Outdated client connected. Make sure to update the clients
> 5957da8d-5087-4262-b0c8-bca0d2cb8fdb: handshake - minexmr.com, 47Zg611h...
> 5957da8d-5087-4262-b0c8-bca0d2cb8fdb: reusing pool connection
> 5957da8d-5087-4262-b0c8-bca0d2cb8fdb: got job from pool
> FLECK: Error while listening for new clients One or more errors occurred.
> FLECK: Listener socket restarting
> FLECK: Server started at ws://0.0.0.0:8181 (actual port 8181)
> FLECK: Listener socket restarted
> FLECK: Error while listening for new clients One or more errors occurred.
> FLECK: Listener socket restarting
> FLECK: Server started at ws://0.0.0.0:8181 (actual port 8181)
> FLECK: Listener socket restarted
> f69e6ba9-cfa5-40fb-9d3b-2fd19a0773a6: reports solved hash
> FLECK: Error while listening for new clients One or more errors occurred.
> FLECK: Listener socket restarting
> FLECK: Server started at ws://0.0.0.0:8181 (actual port 8181)
> FLECK: Listener socket restarted
> f69e6ba9-cfa5-40fb-9d3b-2fd19a0773a6: solved job
> FLECK: Error while listening for new clients One or more errors occurred.
> FLECK: Listener socket restarting
> FLECK: Server started at ws://0.0.0.0:8181 (actual port 8181)
> FLECK: Listener socket restarted
> FLECK: Error while listening for new clients One or more errors occurred.
> FLECK: Listener socket restarting
> FLECK: Server started at ws://0.0.0.0:8181 (actual port 8181)
> FLECK: Listener socket restarted
> FLECK: Error while listening for new clients One or more errors occurred.
> FLECK: Listener socket restarting
> FLECK: Server started at ws://0.0.0.0:8181 (actual port 8181)
> FLECK: Listener socket restarted
> 685afb65-1e10-43e6-a9bf-69dc54cf1e89: reports solved hash
> 685afb65-1e10-43e6-a9bf-69dc54cf1e89: got hash-checked
> FLECK: Error while listening for new clients One or more errors occurred.
>

**Comment by wonchoe** [comment]
ulimit -n 200000
looks like that is help to me

**Comment by paul0921** [comment]
Same thing happens to me on my server. I have around 1200 clients and then this happens

**Comment by paul0921** [comment]
If you look in Program.cs, on line 637 you are able to disable the restart web server option. This let me debug a bit more. Increasing file handles as you suggested didn't improve.

**Comment by notgiven688** [comment]
@paul0921 check soft and hard limits of ulimit. It is 99% a ulimit problem.

**Comment by tgves** [comment]
@paul0921 it's as @notgiven688 mentioned. I also faced this problem and the solution was to increase the soft limit of ulimit ( ulimit -Sn ).

One important thing i'd like to mention, if you run the instance on ubuntu, please be aware that you may have to hard code the soft limit of ulimit, as ubuntu will just reset it to 1024 once you restart your ssh session ( don't ask me why though ).

**Comment by paul0921** [comment]
@tgves I found the solution, sorry I didn't post here. To make it stay after boot, this works on 16.04 for me

sudo sh -c 'cat >> /etc/security/limits.conf' <<EOF

*               hard    rtprio          20

*               soft    rtprio          10

*               hard    nofile          65535

*               soft    nofile          65535

EOF

**Comment by tgves** [comment]
@paul0921 glad you solved it :+1:
