### ISSUE TITLE
Clients are not updted on heartbeat

### ISSUE THREAD

**Issue by sourcedexter** [notgiven688/webminerpool#51]
I have multiple clients connected to the server. I can also see that the hashes are being submitted to the pool, but I Am not able to see the job queue or speed updated on the server logs: 

heartbeat; connections client/pool: 0/0; jobqueue: 0.0k; speed: 0.0kH/s

This is what I get, why is that?

**Comment by notgiven688** [comment]
"connections client/pool: 0/0"

means that no one is connected and that there is no pool connection. I do not know why you get anything submitted to the pool (?!)

**Comment by sourcedexter** [comment]
Even when clients have connected, I get something like: 
heartbeat; connections client/pool: 2/1; jobqueue: 0.0k; speed: 0.0kH/s

I know that clients are connected and are producing hashes, but the speed still says 0.0kH/s . shouldn't it be the hash rate of all the connected clients to the server?

**Comment by gromatl** [comment]
@sourcedexter if you want to know your hashrate if you have less than 100h/s, update server source.
Change **((Double) totalSpeed).ToString ("F1")** to -> ((int) totalSpeed).ToString ()

**Comment by nadal28** [comment]
You should check your hashrate in the pool, not in your server

**Comment by gromatl** [comment]
@nadal28 before trusting the pool your mining on, its always nice to know your real hashrate ;)

**Comment by sourcedexter** [comment]
@gromatl thank you very much. I'll do the change. and you are very right. It is better to know the real hash rate. 
Closing this thread as the issue is solved.
