### ISSUE TITLE
Hashes getting rejected after update

### ISSUE THREAD

**Issue by xnite** [notgiven688/webminerpool#52]
I have downloaded miner.js/worker.js/cn.js and my hashes are getting rejected after the most recent update.
Here is the code I'm using on my website it hasn't changed since last working: https://gist.github.com/xnite/5ce50a068c8e833aefcf2580f8fa4ff5 (the only thing that has changed is that I've re-downloaded the scripts)

**Comment by notgiven688** [comment]
You mine AEON? They had a hard fork which webminerpool supports.  How does your pool.json configuration look like for this pool?

**Comment by notgiven688** [comment]
Another info: New client scripts require you to also update the server is most cases. New server versions are always compatible with old clients.

**Comment by xnite** [comment]
hey @notgiven688 I'm using a webminerpool which has been updated for a different site but it's also setup for my site. It is working for site A but not site B. Site A uses the single compressed webmr.js script, where site B uses the miner.js/worker.js/cn.js scripts.

**Comment by notgiven688** [comment]
@xnite that looks good. I will check the scripts later. Thank you for the report.

**Comment by notgiven688** [comment]
@xnite It works here. That is what I tested: 
1) Cloned the current repo and added your configuration to pools.json
2) started the server and tried to use the miner_raw SDK and the miner_compressed SDK to mine AEON at your server.

Both time I got accepted hashes.
