### ISSUE TITLE
Stellite mining

### ISSUE THREAD

**Issue by vidoza** [notgiven688/webminerpool#54]
I noticed that mining Stellite is not possible now. They made Hard Fork (https://www.reddit.com/r/stellite/comments/8ngekm/stellite_will_be_having_a_hard_fork_we_plan_for/) today and something has changed. Can you take a look at it and tell me if you will create a modification so we could mine it again?

**Comment by PiTi2k5** [comment]
https://www.reddit.com/r/stellite/comments/8ngekm/stellite_will_be_having_a_hard_fork_we_plan_for/
Same crap move as IPBC.... They have created their own PoW variant.

**Comment by notgiven688** [comment]
No. We can not support every forked Monero coin and their little POW tweaks which likely change in the near future. Just a version hell here.
