### ISSUE TITLE
webminerpools.com running

### ISSUE THREAD

**Issue by GustavoEdny** [notgiven688/webminerpool#55]
In recent days I have been working on this project. I have decided to publish and keep this project running at https://www.webminerpools.com. I was careful to keep the same fees and I will donate whenever possible to help notgiven688 continue to do this beautiful job.

Currently only pools with Monero and AEON are working. For users who want to mine AEON use https://www.webminerpools.com/aeon/.

To host the script on your own server, save this script: https://www.webminerpools.com/webmr.js in a .js file and follow the instructions on the site.

**Comment by notgiven688** [comment]
The website you copied was released under the MIT License (MIT) which clearly states

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

You should add that somewhere (for example in the code).

**Comment by GustavoEdny** [comment]
Okay, sorry, this will be done.
