### ISSUE TITLE
WebSocket SSL connection error

### ISSUE THREAD

**Issue by Albermonte** [notgiven688/webminerpool#58]
Hi,

I'm testing the miner and is working perfectly over non-ssl connections, but when I upload it to my server and try an ssl connection I'm getting this error:

```
webminerpool server started

Loaded 44 pools from pools.json.
libhash.so is not available. Checking user submitted hashes disabled.
FLECK: Server started at wss://0.0.0.0:8181 (actual port 8181)
Connecting: [MY IP]
Authenticated [MY IP]
FLECK: Application Error A call to SSPI failed, see inner exception.
```

I'm using the same certificate I'm using on my web but converted to pkcs12 with [https://www.sslshopper.com/ssl-converter.html](https://www.sslshopper.com/ssl-converter.html) since I was using a .crt and .key

How can I fix it? Should I generate again the certificate? How?

Thanks so much.

**Comment by PiTi2k5** [comment]
Generate a new cert on https://www.sslforfree.com/ and than with openssl
For Windows use cmd: 
openssl pkcs12 -export -out "certificate.pfx" -inkey "private.key" -in "certificate.crt" -certfile ca_bundle.crt

**Comment by Albermonte** [comment]
Thanks, it's working now
