### ISSUE TITLE
[QUESTION] Simple doubt about certbot and pkcs12

### ISSUE THREAD

**Issue by nadal28** [notgiven688/webminerpool#61]
Certbot SSL certificates expire every 3 months so I need to run:
`openssl pkcs12 -export -out certificate.pfx -inkey privkey.pem -in cert.pem -certfile chain.pem`
every 3 months?

**Comment by hitmanex** [comment]
no you get a completely new certificate

**Comment by notgiven688** [comment]
certificate.pfx will also be invalid when your certificate gets invalid. You need to update certificate accordingly.

**Comment by nadal28** [comment]
@notgiven688 and also server restart is needed, right?

**Comment by hitmanex** [comment]
of course
