### ISSUE TITLE
Server handshake with pool, but connection immediately closed.

### ISSUE THREAD

**Issue by VidYen** [notgiven688/webminerpool#66]
`ac1d1895-b1dd-4745-aaed-58e172d70241: connected with ip (redacted)
ac1d1895-b1dd-4745-aaed-58e172d70241: handshake - moneroocean.stream, 422QQNhn...
ac1d1895-b1dd-4745-aaed-58e172d70241: initiated new pool connection
422QQNhnhX8hmMEkF3TWePWSvKm6DiV7sS3Za2dXrynsJ1w8U6AzwjEdnewdhmP3CDaqvaS6BjEjGMK9mnumtufvLmz5HJi x gulf.moneroocean.stream
[7/21/2018 6:42:13 AM] heartbeat; connections client/pool: 1/1; jobqueue: 0.0k; speed: 0.0kH/s
ac1d1895-b1dd-4745-aaed-58e172d70241: closed
ac1d1895-b1dd-4745-aaed-58e172d70241: closed a pool connection.`

The client miner says 0 hashes repeatedly.

I got in MoneroOcean's discord and he had me test his server by having my client WSS;// point to his fork server of yours. and my client mined fine and used CPU.

Opened the ports to his as listed 10001 in TCP on the CSF. Did a server reboot. I get not certificate errors on my console (or any errors between the web client and my server).

It's just that my server is talking to MoneroOcean's but it keeps dropping the connection as soon as it handshakes.

Also we tried fr. and us.moneroocea.com but that didn't seem to be the issue.

**Comment by notgiven688** [comment]
Using other servers (supportxmr, minexmr..) works?

**Comment by VidYen** [comment]
Hi, they didn't work either, but I must have messed something up as I used the miner_raw/mine.html and it mines just fine now. Might be the way my server handles output or I might have fat fingered the other file somewhere.

Eitherway... Its working now! Thanks!

**Comment by notgiven688** [comment]
I have to remember the phrase "fat fingered".
