### ISSUE TITLE
How to get started 

### ISSUE THREAD

**Issue by kunkunkunkun** [notgiven688/webminerpool#67]
Hi, notgiven688. It's an amazing job you've for web mining. But, could you elaborate more on how to get started for some beginners like me. thank you very much

**Comment by notgiven688** [comment]
Thank you. Maybe you go step by step. Try to get the script (client side on the browser) running on an external server (see: https://github.com/notgiven688/webminerpool/issues/57) . Play around with it and then try to start your own server (first locally without ssl).

**Comment by BackToPyramidOne** [comment]
@kunkunkunkun I would be happy to help you out, join the discord server https://discord.gg/xa2QBRh

**Comment by kunkunkunkun** [comment]
Thank you very much !

**Comment by kunkunkunkun** [comment]
For those who are also starting, I can share with you how I get started
I'd suggested using ubuntu system as you get more control.
1. Create an Ubuntu virtual desktop in VMware Workstation. (i'm using ubuntu16.04)
2. Get the server done first and then go back miner
3. You can just use a normal text editor for ubuntu 
4. The steps are very clear and easy to follow except for the certificate part which is a bit difficult for beginners. 
 Thanks again to notgiven688 for making this project available to everyone.
