### ISSUE TITLE
What license is webminerpool actually?

### ISSUE THREAD

**Issue by VidYen** [notgiven688/webminerpool#68]
Hi just in case you have a problem with this, I'm going to slap a GPLv2 on my fork because otherwise I have to specify for the parts we going to change and I'm lazy (also because if I put any of it in client stuff on WP repository for a plugin it has to be GPLv2 or later, but I don't think anyone ever checks other than the header says it is) .

I see that there are some MIT and OpenAES Licenses in some parts of the code and generally when people put this on Github and don't include the license they just didn't care one way or another (AKA do as you wish license?), but I felt if you had a problem with me GPLing the fork or you didn't have the rights to, I should know or at least ask for consent.

**So as far as you know or care, can I make my fork GPLv2 license?**

**Comment by VidYen** [comment]
It may not pan out, but we are going to try to add some json stuff.

**Comment by jhabdas** [comment]
@VidYen Close this then go to the nearest bar and start drinking until you cannot stop.

**Comment by VidYen** [comment]
@jhabdas I would like to. I know "no response != consent" but I'm going to file this under "do as you like" license. Unless someone is going to complain about MIT vs GPL dogma as I kind of got my plugin to work with it today. I always over complicate it.

So I'm going to throw what I did on the WP repository unless you guys object. (Not the server part obviously)

BTW the way I reward users for their hashes is actually a terrible one and I'm going to advise against using it for selling items worse anything of value as you can mess with js variables and reward yourself.

But... I got it so it doesn't bother uBlock or Brave so... Ere we go.

**Comment by jhabdas** [comment]
> WP repository for a plugin it has to be GPLv2

That's not entirely true. I've done the research here. Despite what WP says If you land a plug-in, you can and should use AGPL. It's compatible and it's designed to close loopholes in in the other licenses. Network use is distribution.
