### ISSUE TITLE
.js doesn't work in IE 11

### ISSUE THREAD

**Issue by bemini911** [notgiven688/webminerpool#70]
javascript works fine in chrome and Firefox, but in doesn't work in IE 11

\SDK\miner_raw\mine.html
console IE11(F12):
SCRIPT5009: "startMining" undefined
file:mine.html, Ln: 27, col: 7

and \SDK\miner_compressed\mine.html"
console IE11(F12):
clean, but nothing happens, the script is not executed, there is no CPU usage

so what's the problem or am I doing something wrong?

**Comment by PiTi2k5** [comment]
IE11 doesnt support Webassambly/ASM fallback

**Comment by bemini911** [comment]
Thx
