### ISSUE TITLE
Mined block not accepted by monero node

### ISSUE THREAD

**Issue by nox956** [notgiven688/webminerpool#74]
Hi @notgiven688, I have been running a monero pool and also a webminerpool for serveral months, but I am not very sure if it is submitting blocks correctly.

And this is the structure of my system, I assumed problem happened at somewhere between client to webminepool.

> client (browser) > webminerpool > my pool > monero node

I got `mined block failed verification` error from monero node more than 10 times, and I found out it all submitted by webminer, so I make a logger to record every result submitted by webminer also the result accepted by pool side, and it seems the problem is related to webminer.

For example, I got this very weird result with plenty of "0" submitted to pool, and the same webminer client actually submit a lot of valid shares (actually almost all shares seems fine and valid) so the pool will not verify the share everytime, and no surprise it turns out not accepted by monero node.

> 2018/9/14 01:03:54.2508190 : {"id":"257026662674773","job_id":"957201424183490","nonce":"0fe0e06e","result":"f93c000000000000000000000000000000000000000000000000000000000000"}

after converting this result to share difficulty, it equals to 7418290040189390442922095266108521228347106455611542317858772759812488284, this is a much higher value than monero network diff, so it will be considered as a block, but obviously it is invalid, and all error results equal to that difficulty

My concern is I'm not sure if this problem is just a single invalid share or it happens every time when submitting a potential block. The interesting part is when I use the exact same settings and software to run webminepool and a test pool on monero testnet it actually submit block correctly, if you have some idea about this please make sure help me out, thanks a lot!

p.s. my operating system is Ubuntu 16.04 server with Mono 5.14.0 Stable

**Comment by notgiven688** [comment]
@nox956 Thank you for the detailed description of your problem. A few questions:

"mined block failed verification error from monero node more than 10 times"

So basically - if the shares were correct - the webminer found 10 blocks on the main chain. Is this a results you would expect from the hashrate the webminer is producing?

Do you have "users" mining with the webminerpool script? Is there a incentive for them to try to make you think they submitted more work than they actually did, e.g. sending wrong shares?

"f93c000000000000000000000000000000000000000000000000000000000000" is impossible. It would be helpful to know which blob (the actual hashed data) was used to get this result. 

I will try to test the miner on very difficult hashes - trying to reproduce it in any way.

**Comment by nox956** [comment]
@notgiven688 Thank you for the prompt reply!

To the first question: 
My pool's hashrate is around 1MH/s, but less than 10% comes from webminer, and all stats are counted together so I'm not 100% positive about the block amount that webminer had atcually found compare to these invalid shares. 

However in the logs I have donwloaded theres are no blocks found by webminers, so I assumed that webminer may not working correctly for me. 

Another reason to believe so is there are a lot of invalid blocks are found by the same miner, but the only reason this is happening is because it's website has largest hashrate, and my pool actually auto adjust difficulty for miners so the share will be submitted in a consistent target time, so it's website didn't submitted more shares amount than anyone else, but more "share value" instead.

To question 2:
As I mentioned in the first question, these invalid blocks are almost submitted by same miner, but there are still some blocks with same weird difficulty are come from other miners. And I did check the website of our top webminer, it uses correct script and considered to website's traffic I think the hashrate is valid.


And sorry for forgetting to log job info, I'm not very familiar with hashing and C#, and I now started to logging job info (blob, job id, target) as well, if this error happen again I will show you the full detail, thanks for your help again!

**Comment by notgiven688** [comment]
Okay, that are some hints. I will check. 

If we get an actually blob with wrong hash we can maybe easily reproduce that possible failure.

**Comment by nox956** [comment]
Btw, the most recent error happened at finding monero block height 1660558 with target difficulty 274484, I wonder if these information will help you revert to original blob?

**Comment by notgiven688** [comment]
Unfortunately this does not help. Maybe it is a problem with some (weird) browser at some version not able to correctly calculate hashes. In this case you would observe the things you observe. With a blob we could just reproduce it. Any wrong hash is interesting - even if it does not crack the network difficulty.

**Comment by nox956** [comment]
I got 2 errors logged, there are the details down below.

`result: {"id":"186400647898666","job_id":"609219443578745","nonce":"dfb3a6a4","result":"f93c000000000000000000000000000000000000000000000000000000000000"}

job: {"identifier":"job","job_id":"27c301f788a346618662fa2482c258ab","algo":"cn","variant":-1,"blob":"0707ba95a3dd050dab394441056651641fecdf0f7e35cec0ecfd19c754ad94f4f05608f6a82b3700000000080822479256191b336a30107ebf5d459eb6b5fe89bac792aaf1e71e9738d62d04","target":"7d740000"}`


`result: {"id":"917463285470461","job_id":"166832462282785","nonce":"1c04e0db","result":"f93c000000000000000000000000000000000000000000000000000000000000"}

job: {"identifier":"job","job_id":"fd6d2f0debe34ce7aeb6c48b6e3e80f2","algo":"cn","variant":-1,"blob":"0707fdcda3dd05b2469f57403c406fa1f652d136ee8af540b3a26f4ae59e837508d738a12af16d0000000060fa80158fd4025633d69391ca3214b1f8e495ac4174d5dfa07687c68272d2f405","target":"ea760000"}`

**Comment by notgiven688** [comment]
@nox956  Thank you for your effort! I can recalculate these hashes with the "official" binaries and get a different result. That means that the client - for whatever reason - calculates something wrong here. This does not affect in any way other valid shares submitted to you.

Both times the miner reports "f93c000000000000000000000000000000000000000000000000000000000000", maybe there is a pattern. If this does not happen too often, I would not worry.

**Comment by notgiven688** [comment]
@nox956 The webminerpool server gives jobs its own job_id. So this comes from the webminerpool server (send to the browser):
`job: {"identifier":"job","job_id":"27c301f788a346618662fa2482c258ab","algo":"cn","variant":-1,"blob":"0707ba95a3dd050dab394441056651641fecdf0f7e35cec0ecfd19c754ad94f4f05608f6a82b3700000000080822479256191b336a30107ebf5d459eb6b5fe89bac792aaf1e71e9738d62d04","target":"7d740000"}`

And the browser answers something which gets translated back to the original job_id provided by the pool. The webminerpool server then sends this

`result: {"id":"186400647898666","job_id":"609219443578745","nonce":"dfb3a6a4","result":"f93c000000000000000000000000000000000000000000000000000000000000"}
`

to the pool.

**Comment by nox956** [comment]
Just some follow up report, I still got the same wrong share result sometimes so I updated to latest master branch and new webmr.js file hope that will solve the problem, thanks for your hard work @notgiven688 !

**Comment by nox956** [comment]
Very interesting, still getting some wrong shares with same result but diffrent hash from v7, but I can confirm that webminer is finding valid blocks.
