### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by develth** [notgiven688/webminerpool#76]
Hi,

the server already crashed the third time with this message:
![screenshot_20180918-081626__01](https://user-images.githubusercontent.com/3374563/45667997-7bc7c180-bb1b-11e8-8da3-2bef3e110e19.jpg)
Thanks

**Comment by notgiven688** [comment]
Interesting. Could you try changing this line

https://github.com/notgiven688/webminerpool/blob/f44c82ddc220fdfc7c2c05d21524e67ffdb8e3f9/server/Server/PoolConnection.cs#L117

to 

`if (mypc.Closed || !client.Connected || ) return;`

I will investigate further..

**Comment by develth** [comment]
Didn´t had a crash (on both machines). Sometimes there are few days between. I will report!

**Comment by notgiven688** [comment]
@develth I will leave the issue open. Thank you very much!

**Comment by notgiven688** [comment]
Seems to solve the issue and will be added to the master-branch when cn_v2 comes out!
