### ISSUE TITLE
Websocket Connection Failed

### ISSUE THREAD

**Issue by TurnTable904** [notgiven688/webminerpool#77]
Any assistance on getting my server up and running? About 30% of the machines I run are able to browser mine and the others are getting websocket connection failed..
![untitled](https://user-images.githubusercontent.com/36056035/45852738-4c79a600-bd0f-11e8-800f-b0123deb806c.png)

**Comment by PiTi2k5** [comment]
Hello, it is a SSL trust cert error. On which service you created that ssl cert?
I recommend https://www.sslforfree.com/

**Comment by TurnTable904** [comment]
I created it through Powershell.. Will try the site you recommended..

**Comment by PiTi2k5** [comment]
You get 3 files from that authority ---> convert it to .pfx
For example with openssl for windows (copy the 3 files in bin folder of openssl)
CMD command
openssl pkcs12 -export -out "certificate.pfx" -inkey "private.key" -in "certificate.crt" -certfile ca_bundle.crt

**Comment by PiTi2k5** [comment]
https://github.com/notgiven688/webminerpool/blob/master/server/Server/Program.cs#L585
Password needs to match with you cert password

**Comment by TurnTable904** [comment]
I paid GoDaddy for a cert for my website, am I able to use that one?

**Comment by PiTi2k5** [comment]
I dont know GoDaddy, if you can download the cert + private.key you can merge this to a pfx file. But i think its only a setting up a https site on godaddy webinterface? The easiest way is https://www.sslforfree.com/ for free.

**Comment by notgiven688** [comment]
I think this issue can be closed - it is a certificate problem. Nothing to do with wmp directly.

**Comment by TurnTable904** [comment]
Yes, sorry it was a cert issue..
