### ISSUE TITLE
userstats always returns 0

### ISSUE THREAD

**Issue by usrbindoma** [notgiven688/webminerpool#79]
If I request the userstats via websocket connection (in /SDK/other/getuserstats.html) the response is always zero. 

Server response: `{"identifier":"userstats","userid":"testminer","value":0}`

The userid is the right. Userid testminer shows up on the pool as worker. 
Any help on this one? 
Need that feature on the server to check if js miner is really mining.

**Comment by notgiven688** [comment]
The user has to solve some jobs so that the hashing power can be estimated. Leave the client running for a while and see if this solves your problem.
