### ISSUE TITLE
server don't send all hashes?

### ISSUE THREAD

**Issue by wonchoe** [notgiven688/webminerpool#8]
![screenshot_3](https://user-images.githubusercontent.com/32915897/38473133-4860636a-3b50-11e8-8e30-4585b543adf6.png)
looks like a server is not stable, some times hasrate going to 0.00 and after 5-10 minutes everything is great and then again

**Comment by notgiven688** [comment]
do you user your own server?

**Comment by notgiven688** [comment]
It could be just an issue with jobs being too hard and messing with the statistics. How many "pool" connections does the server open up? The server outputs this in the "heartbeat" lines.

**Comment by notgiven688** [comment]
@PiTi2k5 Thank you for the info. What is the donation hashing power? I will apply some fixes which hopefully make the h/s charts on the pools make look nice. In theory the difficulty should not matter - the amount of mined XMR is the same.

**Comment by patrickbau** [comment]
Can you please make it easy on how we host it on our server using proxy
I found it very difficult 
More a little explanation i will appreciate 
Thank you

**Comment by wonchoe** [comment]
![screenshot_1](https://user-images.githubusercontent.com/32915897/38510813-bd8b4d80-3beb-11e8-8608-e8cb75988ae9.png)
it's on own server, i check both option and probably it's not a server problem

**Comment by notgiven688** [comment]
@wonchoe make sure you do not run your server with many clients in "debug" mode - use release. I added a new branch https://github.com/notgiven688/webminerpool/compare/batch_size which sets a maximum number of clients for each connection to a pool, e.g. 1000 miners and a batchsize of 100 will result in 10 pool connections. That should even out the hashrate fluctuations you see.

The "ERR_CONNECTION_RESET" in your screenshot is new to me.

**Comment by wonchoe** [comment]
![screenshot_1](https://user-images.githubusercontent.com/32915897/38627524-cd9f6cee-3d74-11e8-93f2-2a93d63626b8.png)
recompile a server(release) and looks like now is better but still same with graphic. I try on your server and on my server and no difference

**Comment by notgiven688** [comment]
You can try to set a lower batch size or stop worrying about hash fluctuations since they are more or less normal. Which pool are you using? minexmr?

**Comment by wonchoe** [comment]
@notgiven688 got you, thanks)
