### ISSUE TITLE
Invalid hash (CN2) - Monero v9 Testnet

### ISSUE THREAD

**Issue by QuantumLeaper** [notgiven688/webminerpool#81]
I was just testing the latest fork for the fun of it. I setup nodejs-pool in testnet mode (which is on hard fork v9). When submitting shares, it looks like the cn2 variant is not working.

After taking a deeper look, it looks like the resultHash does not match the client/miner provided hashes for cn/2

**Comment by notgiven688** [comment]
@QuantumLeaper Thank you for reporting! Does it work with http://killallasics.moneroworld.com/ ?

**Comment by QuantumLeaper** [comment]
No problem! Just tested KAS, *seems to be working*. However, it's showing I mined an amount of hashes, but not showing an XMR balance. Maybe the shares are invalid on there, too? - Might not have mined enough, I'll try some more tests.
 
Also, was just wondering how cryptonight finds whether or not the miner/pool is using variant 0,1,2? I see there's declarations for Variants 1 & 2, but I don't see how those are called/exchanged between the client and the server. When I manually set the variant in main.c to "let variant = 2;" the hashrate performs at a slower rate (making me think its working), but the hashes still seem to be invalid.

**Comment by notgiven688** [comment]
Thank you for testing! If you set the variant to -1 it detects the variant from the first bits of the blob which needs to be hashed (version is encoded in the header). So the variant should be automatically correct within the second of the fork if you chose "-1". All other values overwrite the auto detection. This is useful for other cryptonight coins.

I still have some ideas how to speed it up but it is quite hard.

**Comment by jhabdas** [comment]
Over the last hour or so it seems MoneroOcean switched over to the new algo (not sure about other pools) and `cn/2` is the value assigned `job.algo` a case `worker.js` currently doesn't handle.

**Comment by jhabdas** [comment]
Over the last hour or so it seems MoneroOcean switched over to the new algo (not sure about other pools) and `cn/2` is the value assigned `job.algo` a case `worker.js` currently doesn't handle.

https://github.com/notgiven688/webminerpool/blob/master/SDK/miner_raw/miner/worker.js#L48-L53

**Comment by jhabdas** [comment]
Over the last hour or so it seems MoneroOcean switched over to the new algo (not sure about other pools) and `cn/2` is the value assigned `job.algo` a case `worker.js` currently doesn't handle resulting in a stream of `algorithm not supported!` log messages in the browser console.

**Comment by VidYen** [comment]
BTW I was having issues until I realized the JS files were cached in the
browser and deleting temp files got it working for me. A little too simple
but I got 3 test machines on our fork and they seemed to be working on cn
v2 now at least on Monero Ocean.

**Comment by ChristianGrieger** [comment]
Our fail its working :) Thanks

**Comment by notgiven688** [comment]
@jhabdas You probably did not update. Keep in mind that there are cached versions -> Updating early makes sense. Try your tests again in "incognito" mode of the browser.

**Comment by jhabdas** [comment]
Thanks all and sorry for the trouble. My issue seems to have been I was missing the server mods made in https://github.com/notgiven688/webminerpool/commit/3ffaad6a02d4ff83d17bdaf26efb52b0a4949f97#diff-30cb8b623b970bbb578319bde4ee4391. I'm still confirming on my end but that's the likely culprit. Appreciate the help and sorry for raising any alarms.
