### ISSUE TITLE
Emscripten latest version

### ISSUE THREAD

**Issue by focaeppe** [notgiven688/webminerpool#84]
I'm using the latest Emscripten "v1.38.13", in the last update you mentioned that you are using the version "1.37.40" 
Is there any difference ? or it's ok to use the latest version for compiling

**Comment by notgiven688** [comment]
@focaeppe Maybe you can compare hashrate values? I observed a regression in speed using the newest version. Other than that you should be fine.

**Comment by focaeppe** [comment]
Tested with both versions of Emscripten "1.37.40" and latest "v1.38.13" there is no big differences, but i prefer the latest version .
