### ISSUE TITLE
How to use hash_cn with xmr-node-proxy?

### ISSUE THREAD

**Issue by slayerulan** [notgiven688/webminerpool#86]
Hello,
I was using xmr-node-proxy with webminerpool but after the recent upgrade, hash_cn has new arguments like variant etc.

What should i write to hash_cn function if i'm using Monero's last fork?

I tried hash_cn(I.blob,B,0,-1); but entering -1 as variant is not working.

Thanks

**Comment by slayerulan** [comment]
I've integrated client js to Snipa22/xmr-node-proxy so that i can use nodejs instead of C# in serverside, it was working before the new fork. After that worker js needed job.algo and job.variant values, i've set algo as "cn" and variant as -1 (i use Monero) but clientside gives wrong hashes. I think i set variant wrong, what's correct values?

Thank you so much

**Comment by notgiven688** [comment]
Okay. This has nothing to do with wmp. A custom implementation. You should be fine by using -1 as variant.
