### ISSUE TITLE
Happy fork day - Cryptonight v2

### ISSUE THREAD

**Issue by notgiven688** [notgiven688/webminerpool#87]
It looks like things are working. Yeah!

**Comment by slayerulan** [comment]
Hello,
Its working but i have a problem in hash_cn, normally your library works smoothly with Snipa22/xmr-node-proxy, i've integrated it. But after the last release, it seems hash_cn variables changed so it doesnt work. I manually entered algo = "cn" and hash_cn variant = -1 (im using latest Monero fork), but it doesnt work, it gives wrong solutions. Can you check issue #86 ? 

Thank you so much

**Comment by focaeppe** [comment]
@notgiven688 Thank you for you hard work ,It does work great but we still facing the 25% drop i hope that you can fix this issue

**Comment by QuantumLeaper** [comment]
Coinhive is pretty much the same hashrate. Maybe 2% better. Great work @notgiven688 !! Going to modify my XNP to net you some donations :)

**Comment by notgiven688** [comment]
@QuantumLeaper Thank You. I also compare to Coinhive from time to time. I noticed that it heavily depends on the system/browser combination. On my Ubuntu system the wmp Firefox version easily beats Coinhive, whereas Chromium loses.
