### ISSUE TITLE
25% hashrate drop since fork

### ISSUE THREAD

**Issue by risoncer** [notgiven688/webminerpool#89]
Excellent work with the miner, but since the fork on oct 18th the hashrate dropped by about 25%. Can it be fixed? Perhaps for a bounty?
Thanks!

**Comment by PiTi2k5** [comment]
There are less options for optimize cn2 for the moment. But the good thing is: Monero Network has an hashdrop = lower overall difficulty = more rewards for less mining hashrate, so right now you has a higher reward with cn2. Bounties are a good thing for new ideas, features and improvements.

**Comment by risoncer** [comment]
@PiTi2k5 , I am profiting from the miner and donating hashrate to @notgiven688, so a bounty to get the previous hashrate to maximize profit is also a good thing. 

I understand that due to changes to the algorithm it might be impossible, but if anyone can do it I'd be willing to add to the bounty around 4 XMR.

**Comment by PiTi2k5** [comment]
No one can get the previous hashrate through webmining. Native miners has the same problem, CNv2 has increased compute requirements (15-20% hashrate drops/decrease - you see it on monero network hashrate). Emscripten/webassambly needs a performance boost, because they can only run on 60/65% of an native program.

**Comment by slayerulan** [comment]
I will add +4.5 XMR to bounty if anyone successfully fixes that problem

**Comment by notgiven688** [comment]
@slayerulan @risoncer Should I open/manage a fund address? ~ 10 XMR will definitely be an incentive for wasm developers. Think about a time-span and some rules. If the bounty is not claimed you get paid back.
