### ISSUE TITLE
hashrate two times lower than before

### ISSUE THREAD

**Issue by cron13** [notgiven688/webminerpool#9]
hi!
before v7 i used github.com/cazala/coin-hive-stratum and my hashrate be ~1200
now I switched to this software and my hashrate drop to ~500 h/s.
why could this happen?

**Comment by notgiven688** [comment]
do you user your own server?

**Comment by cron13** [comment]
i have many notifycations "disconnected from own pool. trying to reconnect.". It's ok?

**Comment by notgiven688** [comment]
This is not a problem. Maybe your problem is connected to issue #8. I will investigate later.
