### ISSUE TITLE
setup steps

### ISSUE THREAD

**Issue by xmrmining** [notgiven688/webminerpool#90]
hello,
i see this error when run server.exe:
 mono webminerpool-master/server/Server/bin/Release_Server/server.exe
webminerpool server started
Developer fee of 3.0% enabled. Thank You.
Could not load pool list from pools.json: Could not find file "/root/pools.json"
also , i can not find "libhash.so" file in hash_cn.

Your description and installation process is not suitable for amateur people.
Please provide more detailed description with examples or commands.
thanks.

**Comment by slayerulan** [comment]
https://github.com/notgiven688/webminerpool/blob/master/server/pools.json

copy this file to ~/pools.json

**Comment by xmrmining** [comment]
thanks. it done.
other problem:
libhash.so is not available. Checking user submitted hashes disabled.
i can not find "libhash.so" file in hash_cn!
also i see this msg when run it : 
FLECK: Server started at ws://0.0.0.0:8181 (actual port 8181)
why this is 0.0.0.0 and not my server ip? websocket dont work :(
i use doker command and output is a hash . what is it?

**Comment by notgiven688** [comment]
> FLECK: Server started at ws://0.0.0.0:8181 (actual port 8181)

It is fine. The server is running on your system. You can ignore the libhash.so message for the moment. 

> Websocket not work :(

?

**Comment by hitmanex** [comment]
ive always ran it without libhash.so

**Comment by xmrmining** [comment]
thanks for all things.
i see always this msg avery 15 or 20 Sec : 
disconnected from dev pool. trying to reconnect.
it is normal ?
i use moneroocean.

**Comment by hitmanex** [comment]
no its not normal
