### ISSUE TITLE
user detail

### ISSUE THREAD

**Issue by xmrmining** [notgiven688/webminerpool#91]
Hi dear friend;
Can I access data such as the how much mine  of each user?
by "userstats" just i see total of hash by user.
thanks

**Comment by VidYen** [comment]
You would need to use the VidYen fork and setup nginx as it does do that.

We needed to specifically track indivial users miner on different sites to
different wallets more like Coinhive.

To make things easier, you could install the VYPS WordPress plugin and let
it track users that way via the point per has system etc etc. (The VidYen
fork does track it on the dat file so you don’t have to have it but you’d
need something to parse it for the users to see which the WP plugin does)
