### ISSUE TITLE
Question about donation code

### ISSUE THREAD

**Issue by VidYen** [notgiven688/webminerpool#93]
Question about your donation system. I know most users either leave or set it to 0% depending, but I'd like to know more about how it works due to trying to make multidonation wallet better.

What is this supposed to do on line 116 on `Program.cs`:

```php
// after that job-age we do not forward dev jobs 
private const int TimeDevJobsAreOld = 600;
```

And this on line 1159:

```php
if (clients.Count > 4 && DevDonation.DonationLevel > double.Epsilon) {
        CConsole.ColorWarning (() =>
             Console.WriteLine ("disconnected from dev pool. trying to reconnect."));
        devJob = new Job ();
        CreateOurself ();
}
````

I'm guessing the first was to stop using a client for dev donation after 10 minutes of being connected. What would happen if you set it to 3600? Would it continue with the donation for an hour? Or would setting it to 0 always create new dev jobs?

And the last one...  Does that mean if there are more than 4 clients connected? It creates a new dev job? What would be the ramifications of setting that higher or lower?

I know your comments says what it does, but I'm not sure of the intention to the actual outcome on the donation end.

Thanks...

-Felty

**Comment by PiTi2k5** [comment]
if (clients.ContainsKey (Guid.Empty)) {
                        if (clients.Count == 1)
                            RemoveClient (Guid.Empty);
                    } else {
                        // we removed ourself because we got disconnected from the pool
                        // make us alive again!
                        if (clients.Count > 4 && DevDonation.DonationLevel > double.Epsilon) {
                            CConsole.ColorWarning (() =>
                                Console.WriteLine ("disconnected from dev pool. trying to reconnect."));
                            devJob = new Job ();
                            CreateOurself ();
                        }
}

That is only a reconnect logic if no 00000000000000000 (dev GUID) found

**Comment by VidYen** [comment]
@PiTi2k5 

Thanks. This helps quite a bit.

Also, I'm exploring the option of running more than one `server.exe` per server but on different ports but with different wallets and then just have the PHP called by the client pick a server at random. 

Back to the `TimeDevJobsAreOld`. What is that checking for? That if a client is connected so long it stops doing devjobs or does it mean the dev job has died and at this point... To go ahead and do another one?

**Comment by PiTi2k5** [comment]
It is only a check for devjob age. Because old devjobs can not be valid and shouldnt be sended to clients.
program.cs line 282 there are to conditions 
if (client == ourself) {
                devJob.Blob = ji.Blob;
                devJob.JobId = jobId;
                devJob.Age = DateTime.Now;
                devJob.Algo = ji.Algo;
                devJob.Target = ji.Target;
devJob.Variant = ji.Variant;

You get a fresh devjob.age by datetime from line 285 so line 332 works fine
if (((DateTime.Now - devJob.Age).TotalSeconds < TimeDevJobsAreOld))
and line 282 if (client == ourself) will be triggered often enoungh for new jobs so line 332 is in good standing
So donation runs constant fine :)

I hope you can a little bit understand :> I am not good in explaning

**Comment by VidYen** [comment]
Hrm... That does. Perhaps I'm just limited to my test environment to only so many browsers open to simulate.

Does this pick a client at random and get the donation from them one at a time?

Or can it do more than one at a time?

**Comment by jhabdas** [comment]
Aside.

> Also, I'm exploring the option of running more than one `server.exe` per server but on different ports but with different wallets and then just have the PHP called by the client pick a server at random.

This, to me, simplifies the logic given the client could perform a round-robin—occasionally stopping on a proxy using a 100% donation three percent of the time.

**Comment by VidYen** [comment]
@jhabdas

Yeah, I'm actually learned a lot in past four months out of necessity and realize putting the multidonation in the same server may be too much effort compared to simply running multiple server on the same VM. Due to the need to track hashes for the site admins, I recently moved the statistics.dat file to the root home folder and each server can read and right from it in case the server crashes and reload and the server the client get is not the original. Plus some nginx allows to proxy ports based on the url request which I just put together in the last 24 hours.

I think I've got most of the info I need to go forward, but I'll leave this open for a short bit if you notgiven688 wants to chime in.

**Comment by PiTi2k5** [comment]
***Offtopic***
Btw, if you prefer a near flat hashrate mining stats with less flucties you should use staticDiff e.g wallet.paymetID+staticDiff check your favorite pool for right staticDiff config. I use staticDiff 5000 since nov 2017 for donations and my users do the same StaticDiff 5000-10000. It runs stable, no pool bans and always nice looking mining stats ;)

On long term mining staticDiff and dynamicDiff has the same payouts, but.... there are looking ugly xD

**Comment by notgiven688** [comment]
I can "chime in" but do not have much more to add: The donation system was designed with one donation address in mind. Changing it may be a bit hacky. The best solution is to simply start another instance of the server with another donation address set. Of course you need to use another port (currently 8181, line 623 in Program.cs). The client then randomly connects to one of the ports if you set the server variable in your javascript code to something like

`var server = "wss://ws1.server:8181/;wss://ws1.server:8282/"`

This seems to be the easiest solution for a low number of donation addresses. 

Happy holidays everyone!

**Comment by VidYen** [comment]
Thanks @notgiven688 

I already had something in my WordPress plugin that does this after checking to see if the server is up (a sort of fail over in the client) so perhaps I can add the weighted random there.

Closing this as I think I've got all the info and idea where to go from here.

Thanks everyone.
