### ISSUE TITLE
Minimal working example don't run in chrome 

### ISSUE THREAD

**Issue by 141801** [notgiven688/webminerpool#94]
client:
[2019/1/5 1:15:02] Connecting...
[2019/1/5 1:15:04] calculated 0 hashes.
[2019/1/5 1:15:06] calculated 0 hashes.

**Comment by 141801** [comment]
How can I see logs

**Comment by 141801** [comment]
Using docker in server side 
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                        NAMES
c9484ee429bc        webminerpool        "./entrypoint.sh"   2 hours ago         Up 2 hours          0.0.0.0:80->80/tcp, 0.0.0.0:8181->8181/tcp   trusting_morse

**Comment by notgiven688** [comment]
What does the chrome debug console say? Does it work with Firefox?

**Comment by 141801** [comment]
> What does the chrome debug console say? Does it work with Firefox?

Thans for your rapidly reply .  chrome debug console say nothing 

Chrome browser
![2019-01-07 0 20 08](https://user-images.githubusercontent.com/42635299/50738072-764dce80-1213-11e9-83c2-bb3c11a544b9.png)

 Html file :
![2019-01-07 0 19 58](https://user-images.githubusercontent.com/42635299/50738077-88c80800-1213-11e9-8c10-7844e29384b5.png)


and the same issue in firefox .
![2019-01-07 0 25 14](https://user-images.githubusercontent.com/42635299/50738088-a8f7c700-1213-11e9-92b6-81af1f1972eb.png)

Docker log:
![2019-01-07 0 20 58](https://user-images.githubusercontent.com/42635299/50738099-ba40d380-1213-11e9-87b9-67a1c16bd892.png)

**Comment by 141801** [comment]
Server is in USA and client is in Japan .so the timestamp is  not the same

**Comment by notgiven688** [comment]
Looks like the browser can connect to the server but the final auth. fails. This is usually a symptom that something with the certificate is wrong. Are you using wss (web socket secure)? Also check the network tab in the chrome console.

**Comment by 141801** [comment]
Thanks ,your advice solved my problem . I checked the logs and found my domain sign failed .

[Mon Jan  7 04:20:10 UTC 2019] Verify finished, start to sign.
[Mon Jan  7 04:20:11 UTC 2019] Sign failed: "detail":"Error creating new cert :: too many certificates already issued for exact set of domains: myfuye.com,www.myfuye.com: see https://l
etsencrypt.org/docs/rate-limits/"


I buy a new domain  vraku.work  and config the  A name of vraku.work and www.vraku.work with the same ip  then I works well 
<img width="696" alt="2019-01-07 16 51 35" src="https://user-images.githubusercontent.com/42635299/50755518-9aa1bd80-129c-11e9-8b44-209379878661.png">

Thanks very much for your help!

**Comment by 141801** [comment]
Another question,I had run the script 3hours, and the log

**Comment by notgiven688** [comment]
It is the estimate(!) of the combined speed of all the browsers mining. Keep in mind that 0.1kH/s=100H/s which is already much for a single client.
