### ISSUE TITLE
Are repo still maintained?

### ISSUE THREAD

**Issue by slayerulan** [notgiven688/webminerpool#96]
As there is new versions on wasm and hashing lib, it could be faster if its updated.

Are repo archived?

**Comment by jhabdas** [comment]
@slayerulan it was updated 2 months ago, as you can see from the commit history. if you have some specific suggestions for the dev please detail them out rather than creating fud.

**Comment by notgiven688** [comment]
Waiting for issues to fix :D This is not one.

**Comment by slayerulan** [comment]
@notgiven688 well i wanted to ping you as there is new versions @ emscripten etc that maybe fasten the hashes/s
